package dev.sterner.witchery.fabric.datagen

import dev.sterner.witchery.Witchery
import dev.sterner.witchery.block.ritual.CommandType
import dev.sterner.witchery.recipe.PendantDataComponentRecipe
import dev.sterner.witchery.recipe.PotionDataComponentTransferRecipe
import dev.sterner.witchery.recipe.ShapelessRecipeWithComponentsBuilder
import dev.sterner.witchery.recipe.TaglockDataComponentTransferRecipe
import dev.sterner.witchery.recipe.brazier.BrazierSummoningRecipeBuilder
import dev.sterner.witchery.recipe.cauldron.CauldronBrewingRecipeBuilder
import dev.sterner.witchery.recipe.cauldron.CauldronCraftingRecipeBuilder
import dev.sterner.witchery.recipe.distillery.DistilleryCraftingRecipeBuilder
import dev.sterner.witchery.recipe.oven.OvenCookingRecipeBuilder
import dev.sterner.witchery.recipe.ritual.RitualRecipe
import dev.sterner.witchery.recipe.ritual.RitualRecipeBuilder
import dev.sterner.witchery.recipe.spinning_wheel.SpinningWheelRecipeBuilder
import dev.sterner.witchery.registry.*
import dev.sterner.witchery.ritual.BindFamiliarRitual
import dev.sterner.witchery.ritual.BindSpectralCreaturesRitual
import dev.sterner.witchery.ritual.PushMobsRitual
import dev.sterner.witchery.ritual.ResurrectFamiliarRitual
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider
import net.minecraft.core.HolderLookup
import net.minecraft.core.NonNullList
import net.minecraft.core.component.DataComponentMap
import net.minecraft.data.recipes.*
import net.minecraft.tags.ItemTags
import net.minecraft.world.entity.EntityType
import net.minecraft.world.item.ItemStack
import net.minecraft.world.item.Items
import net.minecraft.world.item.alchemy.PotionContents
import net.minecraft.world.item.alchemy.Potions
import net.minecraft.world.item.crafting.CraftingBookCategory
import net.minecraft.world.item.crafting.Ingredient
import java.awt.Color
import java.util.concurrent.CompletableFuture

class WitcheryRecipeProvider(output: FabricDataOutput, val registriesFuture: CompletableFuture<HolderLookup.Provider>) :
    FabricRecipeProvider(output, registriesFuture) {

    override fun buildRecipes(exporter: RecipeOutput) {

        val map = DataComponentMap.builder().set(WitcheryDataComponents.HAS_SOUP.get(), true).build()
        val list = NonNullList.create<Ingredient>()
        list.add(Ingredient.of(WitcheryItems.CHALICE.get()))
        list.add(Ingredient.of(WitcheryItems.REDSTONE_SOUP.get()))

        ShapelessRecipeWithComponentsBuilder.create(RecipeCategory.MISC, WitcheryItems.CHALICE.get(), map)
            .offerTo(exporter, Witchery.id("fill_chalice"), list)

        //start SPECIAL
        SpecialRecipeBuilder.special { _: CraftingBookCategory? ->
            TaglockDataComponentTransferRecipe()
        }.save(exporter, "taglock_transfer")

        SpecialRecipeBuilder.special { _: CraftingBookCategory? ->
            PotionDataComponentTransferRecipe()
        }.save(exporter, "potion_transfer")

        SpecialRecipeBuilder.special { _: CraftingBookCategory? ->
            PendantDataComponentRecipe()
        }.save(exporter, "pendant_crafting")
        //end SPECIAL


        SpinningWheelRecipeBuilder.create()
            .addInput(WitcheryItems.DREAM_WEAVER.get())
            .addInput(PotionContents.createItemStack(Items.SPLASH_POTION, Potions.POISON))
            .addInput(PotionContents.createItemStack(Items.SPLASH_POTION, Potions.NIGHT_VISION))
            .addInput(ItemStack(WitcheryItems.TORMENTED_TWINE.get(), 2))
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.DREAM_WEAVER_OF_NIGHTMARES.get())
            .save(exporter, Witchery.id("dream_weaver_of_nightmares"))

        SpinningWheelRecipeBuilder.create()
            .addInput(WitcheryItems.DREAM_WEAVER.get())
            .addInput(PotionContents.createItemStack(Items.SPLASH_POTION, Potions.SLOWNESS))
            .addInput(PotionContents.createItemStack(Items.SPLASH_POTION, Potions.SWIFTNESS))
            .addInput(ItemStack(WitcheryItems.FANCIFUL_THREAD.get(), 2))
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.DREAM_WEAVER_OF_FLEET_FOOT.get())
            .save(exporter, Witchery.id("dream_weaver_of_fleet_foot"))

        SpinningWheelRecipeBuilder.create()
            .addInput(WitcheryItems.DREAM_WEAVER.get())
            .addInput(PotionContents.createItemStack(Items.SPLASH_POTION, Potions.HEALING))
            .addInput(ItemStack(WitcheryItems.MELLIFLUOUS_HUNGER.get(), 1))
            .addInput(ItemStack(WitcheryItems.FANCIFUL_THREAD.get(), 2))
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.DREAM_WEAVER_OF_FASTING.get())
            .save(exporter, Witchery.id("dream_weaver_of_fasting"))

        SpinningWheelRecipeBuilder.create()
            .addInput(WitcheryItems.DREAM_WEAVER.get())
            .addInput(PotionContents.createItemStack(Items.SPLASH_POTION, Potions.WEAKNESS))
            .addInput(PotionContents.createItemStack(Items.SPLASH_POTION, Potions.STRENGTH))
            .addInput(ItemStack(WitcheryItems.FANCIFUL_THREAD.get(), 2))
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.DREAM_WEAVER_OF_IRON_ARM.get())
            .save(exporter, Witchery.id("dream_weaver_of_iron_arm"))

        SpinningWheelRecipeBuilder.create()
            .addInput(Items.HAY_BLOCK)
            .addInput(WitcheryItems.WHIFF_OF_MAGIC.get())
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.GOLDEN_THREAD.get())
            .save(exporter, Witchery.id("golden_thread"))

        SpinningWheelRecipeBuilder.create()
            .addInput(Items.WHITE_WOOL)
            .addInput(WitcheryItems.WHIFF_OF_MAGIC.get())
            .addInput(WitcheryItems.PHANTOM_VAPOR.get())
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.IMPREGNATED_FABRIC.get(), 2)
            .save(exporter, Witchery.id("impregnated_fabric"))

        SpinningWheelRecipeBuilder.create()
            .addInput(WitcheryItems.DISTURBED_COTTON.get())
            .addInput(Items.STRING)
            .addInput(WitcheryItems.REEK_OF_MISFORTUNE.get())
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.TORMENTED_TWINE.get(), 4)
            .save(exporter, Witchery.id("tormented_twine"))

        SpinningWheelRecipeBuilder.create()
            .addInput(WitcheryItems.WISPY_COTTON.get())
            .addInput(Items.STRING)
            .addInput(WitcheryItems.ODOR_OF_PURITY.get())
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.FANCIFUL_THREAD.get(), 4)
            .save(exporter, Witchery.id("fanciful_thread"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(Items.POPPY, Color(255, 50, 50).rgb)
            .addInputWithColor(Items.GOLDEN_CARROT, Color(250, 250, 50).rgb)
            .addInputWithColor(Items.LILY_PAD, Color(50, 250, 50).rgb)
            .addInputWithColor(Items.COCOA_BEANS, Color(95, 75, 10).rgb)
            .addInputWithColor(WitcheryItems.WHIFF_OF_MAGIC.get(), Color(255, 150, 170).rgb)
            .addInputWithColor(WitcheryItems.WATER_ARTICHOKE_GLOBE.get(), Color(255, 110, 250).rgb)
            .setOutput(WitcheryItems.BREW_OF_LOVE.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_love"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(Items.COOKIE, Color(255, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.WHIFF_OF_MAGIC.get(), Color(255, 200, 210).rgb)
            .addInputWithColor(WitcheryItems.ICY_NEEDLE.get(), Color(80, 130, 210).rgb)
            .addInputWithColor(WitcheryItems.BREW_OF_LOVE.get(), Color(255, 150, 170).rgb)
            .addInputWithColor(WitcheryItems.WATER_ARTICHOKE_GLOBE.get(), Color(255, 110, 190).rgb)
            .setOutput(WitcheryItems.BREW_OF_SLEEPING.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_sleeping"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(Items.INK_SAC, Color(40, 40, 50).rgb)
            .addInputWithColor(Items.SLIME_BALL, Color(50, 200, 50).rgb)
            .addInputWithColor(WitcheryItems.WOOD_ASH.get(), Color(250, 150, 50).rgb)
            .addInputWithColor(WitcheryItems.BELLADONNA_FLOWER.get(), Color(195, 75, 110).rgb)
            .addInputWithColor(WitcheryItems.ROWAN_BERRIES.get(), Color(255, 50, 70).rgb)
            .addInputWithColor(WitcheryItems.OIL_OF_VITRIOL.get(), Color(50, 50, 50).rgb)
            .setOutput(WitcheryItems.BREW_OF_INK.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_ink"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(Items.CARROT, Color(250, 150, 50).rgb)
            .addInputWithColor(PotionContents.createItemStack(Items.POTION, Potions.NIGHT_VISION), Color(50, 20, 150).rgb)
            .addInputWithColor(Items.SPIDER_EYE, Color(255, 50, 70).rgb)
            .addInputWithColor(Items.BROWN_MUSHROOM, Color(205, 110, 70).rgb)
            .addInputWithColor(Items.SPIDER_EYE, Color(255, 50, 70).rgb)
            .addInputWithColor(WitcheryItems.ODOR_OF_PURITY.get(), Color(150, 50, 150).rgb)
            .setOutput(WitcheryItems.BREW_OF_REVEALING.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_revealing"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.OIL_OF_VITRIOL.get(), Color(50, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.OIL_OF_VITRIOL.get(), Color(50, 20, 50).rgb)
            .addInputWithColor(WitcheryItems.WOOD_ASH.get(), Color(100, 100, 30).rgb)
            .addInputWithColor(Items.MAGMA_CREAM, Color(205, 110, 70).rgb)
            .addInputWithColor(WitcheryItems.BELLADONNA_FLOWER.get(), Color(255, 50, 170).rgb)
            .addInputWithColor(Items.DANDELION, Color(90, 110, 50).rgb)
            .setOutput(WitcheryItems.BREW_OF_EROSION.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_erosion"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.WOOL_OF_BAT.get(), Color(150, 100, 20).rgb)
            .addInputWithColor(WitcheryItems.OIL_OF_VITRIOL.get(), Color(50, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.MUTANDIS.get(), Color(30, 110, 70).rgb)
            .addInputWithColor(Items.BONE, Color(255, 255, 220).rgb)
            .addInputWithColor(Items.REDSTONE, Color(220, 50, 50).rgb)
            .addInputWithColor(Items.ROTTEN_FLESH, Color(150, 30, 30).rgb)
            .setOutput(WitcheryItems.BREW_OF_RAISING.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_raising"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(Items.GLISTERING_MELON_SLICE, Color(155, 190, 190).rgb)
            .addInputWithColor(Items.SNOWBALL, Color(115, 160, 190).rgb)
            .addInputWithColor(Items.RED_MUSHROOM, Color(160, 150, 250).rgb)
            .addInputWithColor(WitcheryItems.ICY_NEEDLE.get(), Color(115, 160, 190).rgb)
            .addInputWithColor(WitcheryItems.WATER_ARTICHOKE_GLOBE.get(), Color(55, 220, 250).rgb)
            .addInputWithColor(WitcheryItems.ODOR_OF_PURITY.get(), Color(90, 50, 250).rgb)
            .setOutput(WitcheryItems.BREW_OF_FROST.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_frost"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(Items.LILY_PAD, Color(60, 230, 60).rgb)
            .addInputWithColor(Items.INK_SAC, Color(40, 40, 80).rgb)
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(160, 70, 30).rgb)
            .addInputWithColor(WitcheryItems.TEAR_OF_THE_GODDESS.get(), Color(115, 160, 190).rgb)
            .addInputWithColor(WitcheryItems.WATER_ARTICHOKE_GLOBE.get(), Color(55, 220, 250).rgb)
            .addInputWithColor(WitcheryItems.ODOR_OF_PURITY.get(), Color(90, 50, 250).rgb)
            .setOutput(WitcheryItems.BREW_OF_THE_DEPTHS.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_the_depths"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.MELLIFLUOUS_HUNGER.get(), Color(220, 70, 60).rgb)
            .addInputWithColor(WitcheryItems.EMBER_MOSS.get(), Color(220, 40, 80).rgb)
            .addInputWithColor(WitcheryItems.BELLADONNA_FLOWER.get(), Color(160, 70, 230).rgb)
            .addInputWithColor(Items.ROTTEN_FLESH, Color(215, 120, 90).rgb)
            .addInputWithColor(Items.POISONOUS_POTATO, Color(255, 220, 100).rgb)
            .addInputWithColor(Items.SPIDER_EYE, Color(220, 50, 50).rgb)
            .setOutput(WitcheryItems.BREW_OF_WASTING.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_wasting"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(Items.COBWEB, Color(220, 220, 220).rgb)
            .addInputWithColor(Items.DANDELION, Color(220, 220, 80).rgb)
            .addInputWithColor(Items.RED_MUSHROOM, Color(210, 70, 130).rgb)
            .addInputWithColor(WitcheryItems.WHIFF_OF_MAGIC.get(), Color(215, 220, 220).rgb)
            .addInputWithColor(WitcheryItems.WOOL_OF_BAT.get(), Color(205, 160, 100).rgb)
            .addInputWithColor(WitcheryItems.BELLADONNA_FLOWER.get(), Color(220, 220, 220).rgb)
            .setOutput(WitcheryItems.BREW_OF_WEBS.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("brew_of_webs"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(Items.REDSTONE, Color(255, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.DROP_OF_LUCK.get(), Color(50, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.WOOL_OF_BAT.get(), Color(150, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.TONGUE_OF_DOG.get(), Color(255, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.BELLADONNA_FLOWER.get(), Color(255, 50, 170).rgb)
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(255, 50, 50).rgb)
            .setOutput(WitcheryItems.REDSTONE_SOUP.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("redstone_soup"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.REDSTONE_SOUP.get(), Color(255, 50, 50).rgb)
            .addInputWithColor(Items.FEATHER, Color(250, 250, 250).rgb)
            .addInputWithColor(
                PotionContents.createItemStack(Items.POTION, Potions.SWIFTNESS),
                Color(125, 165, 250).rgb
            )
            .addInputWithColor(WitcheryItems.WOOL_OF_BAT.get(), Color(150, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.BELLADONNA_FLOWER.get(), Color(255, 180, 10).rgb)
            .setOutput(WitcheryItems.FLYING_OINTMENT.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("flying_ointment"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.REDSTONE_SOUP.get(), Color(255, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.ATTUNED_STONE.get(), Color(255, 50, 250).rgb)
            .addInputWithColor(
                PotionContents.createItemStack(Items.POTION, Potions.REGENERATION),
                Color(125, 165, 250).rgb
            )
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(150, 50, 50).rgb)
            .addInputWithColor(Items.GOLDEN_APPLE, Color(180, 180, 0).rgb)
            .addInputWithColor(WitcheryItems.ROWAN_SAPLING.get(), Color(55, 250, 10).rgb)
            .setOutput(WitcheryItems.SOUL_OF_THE_WORLD.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("soul_of_the_world"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.REDSTONE_SOUP.get(), Color(255, 50, 50).rgb)
            .addInputWithColor(
                PotionContents.createItemStack(Items.POTION, Potions.STRONG_HARMING),
                Color(225, 165, 50).rgb
            )
            .addInputWithColor(WitcheryItems.DEMON_HEART.get(), Color(255, 50, 20).rgb)
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(150, 50, 50).rgb)
            .addInputWithColor(Items.FERMENTED_SPIDER_EYE, Color(155, 150, 10).rgb)
            .addInputWithColor(WitcheryItems.REFINED_EVIL.get(), Color(255, 100, 10).rgb)
            .addInputWithColor(Items.BLAZE_ROD, Color(255, 50, 10).rgb)
            .setOutput(WitcheryItems.INFERNAL_ANIMUS.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("infernal_animus"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.REDSTONE_SOUP.get(), Color(255, 50, 50).rgb)
            .addInputWithColor(
                PotionContents.createItemStack(Items.POTION, Potions.LONG_SWIFTNESS),
                Color(60, 165, 250).rgb
            )
            .addInputWithColor(Items.ENDER_EYE, Color(4, 250, 130).rgb)
            .addInputWithColor(Items.ENDER_EYE, Color(10, 250, 90).rgb)
            .addInputWithColor(WitcheryItems.DROP_OF_LUCK.get(), Color(50, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.WOOL_OF_BAT.get(), Color(255, 100, 255).rgb)
            .setOutput(WitcheryItems.SPIRIT_OF_OTHERWHERE.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("spirit_of_otherwhere"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.REDSTONE_SOUP.get(), Color(255, 50, 50).rgb)
            .addInputWithColor(
                PotionContents.createItemStack(Items.POTION, Potions.LONG_INVISIBILITY),
                Color(60, 165, 250).rgb
            )
            .addInputWithColor(
                PotionContents.createItemStack(Items.POTION, Potions.LONG_FIRE_RESISTANCE),
                Color(255, 160, 60).rgb
            )
            .addInputWithColor(WitcheryItems.EMBER_MOSS.get(), Color(255, 180, 90).rgb)
            .addInputWithColor(Items.TORCH, Color(250, 250, 50).rgb)
            .addInputWithColor(WitcheryItems.TONGUE_OF_DOG.get(), Color(200, 200, 255).rgb)
            .setOutput(WitcheryItems.GHOST_OF_THE_LIGHT.get())
            .setAltarPower(100)
            .save(exporter, Witchery.id("ghost_of_the_light"))

        CauldronBrewingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.FANCIFUL_THREAD.get(), Color(200,150,100).rgb)
            .addInputWithColor(WitcheryItems.SPANISH_MOSS.get(), Color(100,200,100).rgb)
            .addInputWithColor(WitcheryItems.WATER_ARTICHOKE_GLOBE.get(), Color(100,100,200).rgb)
            .addInputWithColor(WitcheryItems.GLINTWEED.get(), Color(250, 250, 50).rgb)
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(150,100,5).rgb)
            .addInputWithColor(WitcheryItems.WOOL_OF_BAT.get(), Color(80,150,255).rgb)
            .setOutput(WitcheryItems.BREW_FLOWING_SPIRIT.get())
            .setAltarPower(100)
            .setDimensionKey(setOf("witchery:dream_world", "witchery:nightmare_world"))
            .save(exporter, Witchery.id("brew_of_flowing_spirit"))



        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.RITUAL_CHALK.get(), 2)
            .pattern("ATA")
            .pattern("AGA")
            .pattern("AGA")
            .define('A', WitcheryItems.WOOD_ASH.get())
            .define('T', WitcheryItems.TEAR_OF_THE_GODDESS.get())
            .define('G', WitcheryItems.GYPSUM.get())
            .unlockedBy("has_wood_ash", has(WitcheryItems.WOOD_ASH.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.DREAM_WEAVER.get())
            .pattern(" P ")
            .pattern("TIT")
            .pattern("T T")
            .define('P', WitcheryItems.PHANTOM_VAPOR.get())
            .define('T', WitcheryItems.TORMENTED_TWINE.get())
            .define('I', Items.ITEM_FRAME)
            .unlockedBy("has_twine", has(WitcheryItems.TORMENTED_TWINE.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.CLAY_JAR.get(), 4)
            .pattern(" C ")
            .pattern("CCC")
            .define('C', Items.CLAY_BALL)
            .unlockedBy("has_clay", has(Items.CLAY_BALL))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.IRON_WITCHES_OVEN.get())
            .pattern(" B ")
            .pattern("III")
            .pattern("IBI")
            .define('B', Items.IRON_BARS)
            .define('I', Items.IRON_INGOT)
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.COPPER_WITCHES_OVEN.get())
            .pattern(" T ")
            .pattern("CCC")
            .pattern("CTC")
            .define('T', Items.COPPER_TRAPDOOR)
            .define('C', Items.COPPER_INGOT)
            .unlockedBy("has_copper", has(Items.COPPER_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.IRON_WITCHES_OVEN_FUME_EXTENSION.get())
            .pattern("BLB")
            .pattern("BGB")
            .pattern("IAI")
            .define('B', Items.BUCKET)
            .define('L', Items.LAVA_BUCKET)
            .define('G', Items.GLOWSTONE)
            .define('A', Items.IRON_BARS)
            .define('I', Items.IRON_BLOCK)
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.COPPER_WITCHES_OVEN_FUME_EXTENSION.get())
            .pattern("BLB")
            .pattern("BGB")
            .pattern("IAI")
            .define('B', Items.LIGHTNING_ROD)
            .define('L', Items.LAVA_BUCKET)
            .define('G', Items.GLOWSTONE)
            .define('A', Items.COPPER_TRAPDOOR)
            .define('I', Items.COPPER_BLOCK)
            .unlockedBy("has_copper", has(Items.COPPER_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.DEEPSLATE_ALTAR_BLOCK.get(), 3)
            .pattern("BWE")
            .pattern("DRD")
            .pattern("DRD")
            .define('B', WitcheryItems.BREATH_OF_THE_GODDESS.get())
            .define('E', WitcheryItems.EXHALE_OF_THE_HORNED_ONE.get())
            .define('W', Items.POTION)
            .define('D', Items.DEEPSLATE_BRICKS)
            .define('R', WitcheryTags.ROWAN_LOG_ITEMS)
            .unlockedBy("has_logs", has(WitcheryTags.ROWAN_LOG_ITEMS))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.GUIDEBOOK.get())
            .pattern(" W ")
            .pattern("IBF")
            .pattern(" C ")
            .define('W', WitcheryItems.BELLADONNA_FLOWER.get())
            .define('I', Items.INK_SAC)
            .define('B', Items.BOOK)
            .define('F', Items.FEATHER)
            .define('C', ItemTags.COALS)
            .unlockedBy("has_book", has(Items.BOOK))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.ROWAN_STAIRS.get(), 4)
            .pattern("P  ")
            .pattern("PP ")
            .pattern("PPP")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.ROWAN_SLAB.get(), 6)
            .pattern("PPP")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.ROWAN_FENCE.get(), 3)
            .pattern("PSP")
            .pattern("PSP")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.ROWAN_FENCE_GATE.get())
            .pattern("SPS")
            .pattern("SPS")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.ROWAN_PRESSURE_PLATE.get())
            .pattern("PP")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.ROWAN_DOOR.get(), 3)
            .pattern("PP")
            .pattern("PP")
            .pattern("PP")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.ROWAN_TRAPDOOR.get(), 2)
            .pattern("PPP")
            .pattern("PPP")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.ROWAN_SIGN.get(), 3)
            .pattern("PPP")
            .pattern("PPP")
            .pattern(" S ")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.ROWAN_HANGING_SIGN.get(), 6)
            .pattern("C C")
            .pattern("LLL")
            .pattern("LLL")
            .define('L', WitcheryItems.STRIPPED_ROWAN_LOG.get())
            .define('C', Items.CHAIN)
            .unlockedBy("has_logs", has(WitcheryTags.ROWAN_LOG_ITEMS))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.TRANSPORTATION, WitcheryItems.ROWAN_BOAT.get())
            .pattern("P P")
            .pattern("PPP")
            .define('P', WitcheryItems.ROWAN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.ALDER_STAIRS.get(), 4)
            .pattern("P  ")
            .pattern("PP ")
            .pattern("PPP")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.ALDER_SLAB.get(), 6)
            .pattern("PPP")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.ALDER_FENCE.get(), 3)
            .pattern("PSP")
            .pattern("PSP")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.ALDER_FENCE_GATE.get())
            .pattern("SPS")
            .pattern("SPS")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.ALDER_PRESSURE_PLATE.get())
            .pattern("PP")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.ALDER_DOOR.get(), 3)
            .pattern("PP")
            .pattern("PP")
            .pattern("PP")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.ALDER_TRAPDOOR.get(), 2)
            .pattern("PPP")
            .pattern("PPP")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.ALDER_SIGN.get(), 3)
            .pattern("PPP")
            .pattern("PPP")
            .pattern(" S ")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.ALDER_HANGING_SIGN.get(), 6)
            .pattern("C C")
            .pattern("LLL")
            .pattern("LLL")
            .define('L', WitcheryItems.STRIPPED_ALDER_LOG.get())
            .define('C', Items.CHAIN)
            .unlockedBy("has_logs", has(WitcheryTags.ALDER_LOG_ITEMS))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.TRANSPORTATION, WitcheryItems.ALDER_BOAT.get())
            .pattern("P P")
            .pattern("PPP")
            .define('P', WitcheryItems.ALDER_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.HAWTHORN_STAIRS.get(), 4)
            .pattern("P  ")
            .pattern("PP ")
            .pattern("PPP")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.HAWTHORN_SLAB.get(), 6)
            .pattern("PPP")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.HAWTHORN_FENCE.get(), 3)
            .pattern("PSP")
            .pattern("PSP")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.HAWTHORN_FENCE_GATE.get())
            .pattern("SPS")
            .pattern("SPS")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.HAWTHORN_PRESSURE_PLATE.get())
            .pattern("PP")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.HAWTHORN_DOOR.get(), 3)
            .pattern("PP")
            .pattern("PP")
            .pattern("PP")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.REDSTONE, WitcheryItems.HAWTHORN_TRAPDOOR.get(), 2)
            .pattern("PPP")
            .pattern("PPP")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.HAWTHORN_SIGN.get(), 3)
            .pattern("PPP")
            .pattern("PPP")
            .pattern(" S ")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .define('S', Items.STICK)
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.HAWTHORN_HANGING_SIGN.get(), 6)
            .pattern("C C")
            .pattern("LLL")
            .pattern("LLL")
            .define('L', WitcheryItems.STRIPPED_HAWTHORN_LOG.get())
            .define('C', Items.CHAIN)
            .unlockedBy("has_logs", has(WitcheryTags.HAWTHORN_LOG_ITEMS))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.TRANSPORTATION, WitcheryItems.HAWTHORN_BOAT.get())
            .pattern("P P")
            .pattern("PPP")
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.WHITE_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.WHITE_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.ORANGE_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.ORANGE_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.MAGENTA_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.MAGENTA_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.LIGHT_BLUE_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.LIGHT_BLUE_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.YELLOW_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.YELLOW_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.LIME_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.LIME_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.PINK_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.PINK_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.GRAY_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.GRAY_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.LIGHT_GRAY_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.LIGHT_GRAY_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.CYAN_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.CYAN_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.PURPLE_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.PURPLE_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.BLUE_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.BLUE_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.BROWN_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.BROWN_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.GREEN_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.GREEN_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.RED_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.RED_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.BLACK_IRON_CANDELABRA.get())
            .pattern("CCC")
            .pattern("IAI")
            .pattern(" I ")
            .define('C', Items.BLACK_CANDLE)
            .define('I', Items.IRON_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.ATTUNED_STONE.get())
            .pattern("W")
            .pattern("A")
            .pattern("L")
            .define('W', WitcheryItems.WHIFF_OF_MAGIC.get())
            .define('A', Items.AMETHYST_SHARD)
            .define('L', Items.LAVA_BUCKET)
            .unlockedBy("has_amethyst", has(Items.AMETHYST_SHARD))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.TOOLS, WitcheryItems.ARTHANA.get())
            .pattern(" I ")
            .pattern("NEN")
            .pattern(" S ")
            .define('I', Items.GOLD_INGOT)
            .define('N', Items.GOLD_NUGGET)
            .define('E', Items.EMERALD)
            .define('S', Items.BONE)
            .unlockedBy("has_gold", has(Items.GOLD_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.DECORATIONS, WitcheryItems.CHALICE.get())
            .pattern("NAN")
            .pattern("NIN")
            .pattern(" I ")
            .define('I', Items.GOLD_INGOT)
            .define('N', Items.GOLD_NUGGET)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_gold", has(Items.GOLD_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.SPINNING_WHEEL.get())
            .pattern("IIW")
            .pattern("IIH")
            .pattern("PAH")
            .define('H', WitcheryItems.HAWTHORN_LOG.get())
            .define('P', WitcheryItems.HAWTHORN_PLANKS.get())
            .define('I', Items.ITEM_FRAME)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .define('W', ItemTags.WOOL)
            .unlockedBy("has_moss", has(WitcheryItems.SPANISH_MOSS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.POPPET.get())
            .pattern("WSW")
            .pattern("BST")
            .pattern("W W")
            .define('S', WitcheryItems.SPANISH_MOSS.get())
            .define('B', WitcheryItems.BONE_NEEDLE.get())
            .define('W', Items.HAY_BLOCK)
            .define('T', Items.STRING)
            .unlockedBy("has_moss", has(WitcheryItems.SPANISH_MOSS.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.DEATH_PROTECTION_POPPET.get())
            .pattern("DGP")
            .pattern("GCG")
            .pattern(" G ")
            .define('D', WitcheryItems.DROP_OF_LUCK.get())
            .define('P', WitcheryItems.PHANTOM_VAPOR.get())
            .define('C', WitcheryItems.POPPET.get())
            .define('G', Items.GOLD_NUGGET)
            .unlockedBy("has_poppet", has(WitcheryItems.POPPET.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.VOODOO_POPPET.get())
            .pattern(" F ")
            .pattern("BPM")
            .pattern(" E ")
            .define('F', Items.FERMENTED_SPIDER_EYE)
            .define('M', WitcheryItems.MANDRAKE_ROOT.get())
            .define('P', WitcheryItems.POPPET.get())
            .define('E', WitcheryItems.EXHALE_OF_THE_HORNED_ONE.get())
            .define('B', WitcheryItems.BELLADONNA_FLOWER.get())
            .unlockedBy("has_poppet", has(WitcheryItems.POPPET.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.ARMOR_PROTECTION_POPPET.get())
            .pattern(" F ")
            .pattern("LPL")
            .pattern(" E ")
            .define('F', WitcheryItems.REEK_OF_MISFORTUNE.get())
            .define('L', WitcheryItems.DROP_OF_LUCK.get())
            .define('P', WitcheryItems.POPPET.get())
            .define('E', WitcheryItems.PHANTOM_VAPOR.get())
            .unlockedBy("has_poppet", has(WitcheryItems.POPPET.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.HUNGER_PROTECTION_POPPET.get())
            .pattern(" F ")
            .pattern("MPM")
            .pattern(" F ")
            .define('F', Items.ROTTEN_FLESH)
            .define('M', Items.GLISTERING_MELON_SLICE)
            .define('P', WitcheryItems.POPPET.get())
            .unlockedBy("has_poppet", has(WitcheryItems.POPPET.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.VOODOO_PROTECTION_POPPET.get())
            .pattern("YSR")
            .pattern("BPM")
            .pattern("RWY")
            .define('Y', Items.DANDELION)
            .define('S', Items.RED_MUSHROOM)
            .define('R', Items.POPPY)
            .define('W', Items.BROWN_MUSHROOM)
            .define('P', WitcheryItems.POPPET.get())
            .define('B', WitcheryItems.BELLADONNA_FLOWER.get())
            .define('M', WitcheryItems.MANDRAKE_ROOT.get())
            .unlockedBy("has_poppet", has(WitcheryItems.POPPET.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.VAMPIRIC_POPPET.get())
            .pattern(" D ")
            .pattern("LPL")
            .pattern(" E ")
            .define('E', WitcheryItems.EXHALE_OF_THE_HORNED_ONE.get())
            .define('L', WitcheryItems.WOOL_OF_BAT.get())
            .define('P', WitcheryItems.POPPET.get())
            .define('D', WitcheryItems.PHANTOM_VAPOR.get())
            .unlockedBy("has_poppet", has(WitcheryItems.POPPET.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.BROOM.get())
            .pattern("L")
            .pattern("L")
            .pattern("H")
            .define('H', Items.HAY_BLOCK)
            .define('L', WitcheryItems.ALDER_LOG.get())
            .unlockedBy("has_alder", has(WitcheryItems.ALDER_LOG.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.OXFORD_BOOTS.get())
            .pattern("W W")
            .pattern("W W")
            .define('W', WitcheryItems.WOVEN_CRUOR.get())
            .unlockedBy("has_cruor", has(WitcheryItems.WOVEN_CRUOR.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.TROUSERS.get())
            .pattern("WWW")
            .pattern("W W")
            .pattern("W W")
            .define('W', WitcheryItems.WOVEN_CRUOR.get())
            .unlockedBy("has_cruor", has(WitcheryItems.WOVEN_CRUOR.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.DRESS_COAT.get())
            .pattern("W W")
            .pattern("WWW")
            .pattern("WWW")
            .define('W', WitcheryItems.WOVEN_CRUOR.get())
            .unlockedBy("has_cruor", has(WitcheryItems.WOVEN_CRUOR.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.TOP_HAT.get())
            .pattern("WWW")
            .pattern("W W")
            .define('W', WitcheryItems.WOVEN_CRUOR.get())
            .unlockedBy("has_cruor", has(WitcheryItems.WOVEN_CRUOR.get()))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.TOOLS, WitcheryItems.BONE_NEEDLE.get())
            .requires(Items.BONE)
            .requires(Items.FLINT)
            .unlockedBy("has_flint", has(Items.FLINT))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.TOOLS, WitcheryItems.WAYSTONE.get())
            .requires(WitcheryItems.BONE_NEEDLE.get())
            .requires(Items.QUARTZ)
            .unlockedBy("has_flint", has(Items.FLINT))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.ROWAN_PLANKS.get(), 4)
            .requires(WitcheryTags.ROWAN_LOG_ITEMS)
            .unlockedBy("has_logs", has(WitcheryTags.ROWAN_LOG_ITEMS))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.REDSTONE, WitcheryItems.ROWAN_BUTTON.get())
            .requires(WitcheryItems.ROWAN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.TRANSPORTATION, WitcheryItems.ROWAN_CHEST_BOAT.get())
            .requires(WitcheryItems.ROWAN_BOAT.get())
            .requires(Items.CHEST)
            .unlockedBy("has_planks", has(WitcheryItems.ROWAN_PLANKS.get()))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.ALDER_PLANKS.get(), 4)
            .requires(WitcheryTags.ALDER_LOG_ITEMS)
            .unlockedBy("has_logs", has(WitcheryTags.ALDER_LOG_ITEMS))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.REDSTONE, WitcheryItems.ALDER_BUTTON.get())
            .requires(WitcheryItems.ALDER_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.TRANSPORTATION, WitcheryItems.ALDER_CHEST_BOAT.get())
            .requires(WitcheryItems.ALDER_BOAT.get())
            .requires(Items.CHEST)
            .unlockedBy("has_planks", has(WitcheryItems.ALDER_PLANKS.get()))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.BUILDING_BLOCKS, WitcheryItems.HAWTHORN_PLANKS.get(), 4)
            .requires(WitcheryTags.HAWTHORN_LOG_ITEMS)
            .unlockedBy("has_logs", has(WitcheryTags.HAWTHORN_LOG_ITEMS))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.REDSTONE, WitcheryItems.HAWTHORN_BUTTON.get())
            .requires(WitcheryItems.HAWTHORN_PLANKS.get())
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.TRANSPORTATION, WitcheryItems.HAWTHORN_CHEST_BOAT.get())
            .requires(WitcheryItems.HAWTHORN_BOAT.get())
            .requires(Items.CHEST)
            .unlockedBy("has_planks", has(WitcheryItems.HAWTHORN_PLANKS.get()))
            .save(exporter)

        ShapelessRecipeBuilder.shapeless(RecipeCategory.DECORATIONS, WitcheryItems.IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter, WitcheryItems.IRON_CANDELABRA.id.withSuffix("_undyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.WHITE_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.WHITE_DYE)
            .group("dyed_candle")
            .unlockedBy("has_white_dye", has(Items.WHITE_DYE))
            .save(exporter, WitcheryItems.WHITE_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.ORANGE_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.ORANGE_DYE)
            .group("dyed_candle")
            .unlockedBy("has_orange_dye", has(Items.ORANGE_DYE))
            .save(exporter, WitcheryItems.ORANGE_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.MAGENTA_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.MAGENTA_DYE)
            .group("dyed_candle")
            .unlockedBy("has_magenta_dye", has(Items.MAGENTA_DYE))
            .save(exporter, WitcheryItems.MAGENTA_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.LIGHT_BLUE_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.LIGHT_BLUE_DYE)
            .group("dyed_candle")
            .unlockedBy("has_light_blue_dye", has(Items.LIGHT_BLUE_DYE))
            .save(exporter, WitcheryItems.LIGHT_BLUE_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.YELLOW_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.YELLOW_DYE)
            .group("dyed_candle")
            .unlockedBy("has_yellow_dye", has(Items.YELLOW_DYE))
            .save(exporter, WitcheryItems.YELLOW_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.LIME_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.LIME_DYE)
            .group("dyed_candle")
            .unlockedBy("has_lime_dye", has(Items.LIME_DYE))
            .save(exporter, WitcheryItems.LIME_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.PINK_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.PINK_DYE)
            .group("dyed_candle")
            .unlockedBy("has_pink_dye", has(Items.PINK_DYE))
            .save(exporter, WitcheryItems.PINK_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.GRAY_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.GRAY_DYE)
            .group("dyed_candle")
            .unlockedBy("has_gray_dye", has(Items.GRAY_DYE))
            .save(exporter, WitcheryItems.GRAY_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.LIGHT_GRAY_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.LIGHT_GRAY_DYE)
            .group("dyed_candle")
            .unlockedBy("has_light_gray_dye", has(Items.LIGHT_GRAY_DYE))
            .save(exporter, WitcheryItems.LIGHT_GRAY_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.CYAN_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.CYAN_DYE)
            .group("dyed_candle")
            .unlockedBy("has_cyan_dye", has(Items.CYAN_DYE))
            .save(exporter, WitcheryItems.CYAN_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.PURPLE_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.PURPLE_DYE)
            .group("dyed_candle")
            .unlockedBy("has_purple_dye", has(Items.PURPLE_DYE))
            .save(exporter, WitcheryItems.PURPLE_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.BLUE_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.BLUE_DYE)
            .group("dyed_candle")
            .unlockedBy("has_blue_dye", has(Items.BLUE_DYE))
            .save(exporter, WitcheryItems.BLUE_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.BROWN_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.BROWN_DYE)
            .group("dyed_candle")
            .unlockedBy("has_brown_dye", has(Items.BROWN_DYE))
            .save(exporter, WitcheryItems.BROWN_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.GREEN_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.GREEN_DYE)
            .group("dyed_candle")
            .unlockedBy("has_green_dye", has(Items.GREEN_DYE))
            .save(exporter, WitcheryItems.GREEN_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.RED_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.RED_DYE)
            .group("dyed_candle")
            .unlockedBy("has_red_dye", has(Items.RED_DYE))
            .save(exporter, WitcheryItems.RED_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, WitcheryItems.BLACK_IRON_CANDELABRA.get())
            .requires(WitcheryTags.CANDELABRA_ITEMS)
            .requires(Items.BLACK_DYE)
            .group("dyed_candle")
            .unlockedBy("has_black_dye", has(Items.BLACK_DYE))
            .save(exporter, WitcheryItems.BLACK_IRON_CANDELABRA.id.withSuffix("_dyed"))

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, Items.BONE_MEAL, 6)
            .requires(WitcheryItems.WOOD_ASH.get(), 6)
            .requires(Items.BONE, 1)
            .unlockedBy("has_wood_ash", has(WitcheryItems.WOOD_ASH.get()))
            .save(exporter, "witchery:bone_meal_6")

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, Items.BONE_MEAL, 7)
            .requires(WitcheryItems.WOOD_ASH.get(), 8)
            .requires(Items.BONE, 1)
            .unlockedBy("has_wood_ash", has(WitcheryItems.WOOD_ASH.get()))
            .save(exporter, "witchery:bone_meal_7")

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, Items.BONE_MEAL, 5)
            .requires(WitcheryItems.WOOD_ASH.get(), 4)
            .requires(Items.BONE, 1)
            .unlockedBy("has_wood_ash", has(WitcheryItems.WOOD_ASH.get()))
            .save(exporter, "witchery:bone_meal_5")

        ShapelessRecipeBuilder.shapeless(RecipeCategory.MISC, Items.BONE_MEAL, 4)
            .requires(WitcheryItems.WOOD_ASH.get(), 2)
            .requires(Items.BONE, 1)
            .unlockedBy("has_wood_ash", has(WitcheryItems.WOOD_ASH.get()))
            .save(exporter, "witchery:bone_meal_4")

        SimpleCookingRecipeBuilder.smelting(
            Ingredient.of(WitcheryItems.CLAY_JAR.get()),
            RecipeCategory.MISC, WitcheryItems.JAR.get(), 0.3f, 200
        )
            .unlockedBy("has_clay_jar", has(WitcheryItems.CLAY_JAR.get()))
            .save(exporter)


        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.DISTILLERY.get())
            .pattern("JIJ")
            .pattern("III")
            .pattern("GAG")
            .define('J', WitcheryItems.JAR.get())
            .define('I', Items.IRON_INGOT)
            .define('G', Items.GOLD_INGOT)
            .define('A', WitcheryItems.ATTUNED_STONE.get())
            .unlockedBy("has_attuned", has(WitcheryItems.ATTUNED_STONE.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.CAULDRON.get())
            .pattern("I I")
            .pattern("III")
            .pattern(" C ")
            .define('I', Items.IRON_INGOT)
            .define('C', Items.CAMPFIRE)
            .unlockedBy("has_iron", has(Items.IRON_INGOT))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.COPPER_CAULDRON.get())
            .pattern("I I")
            .pattern("IBI")
            .pattern(" C ")
            .define('I', Items.COPPER_INGOT)
            .define('B', Items.COPPER_BLOCK)
            .define('C', Items.CAMPFIRE)
            .unlockedBy("has_copper", has(Items.COPPER_INGOT))
            .save(exporter)


        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.WITCHES_ROBES.get())
            .pattern("I I")
            .pattern("ISI")
            .pattern("III")
            .define('I', WitcheryItems.IMPREGNATED_FABRIC.get())
            .define('S', WitcheryItems.GOLDEN_THREAD.get())
            .unlockedBy("has_impregnated", has(WitcheryItems.IMPREGNATED_FABRIC.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.WITCHES_HAT.get())
            .pattern(" I ")
            .pattern("SIS")
            .pattern("IGI")
            .define('I', WitcheryItems.IMPREGNATED_FABRIC.get())
            .define('S', WitcheryItems.GOLDEN_THREAD.get())
            .define('G', Items.GLOWSTONE_DUST)
            .unlockedBy("has_impregnated", has(WitcheryItems.IMPREGNATED_FABRIC.get()))
            .save(exporter)


        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.WITCHES_SLIPPERS.get())
            .pattern("S S")
            .pattern("I I")
            .define('I', WitcheryItems.IMPREGNATED_FABRIC.get())
            .define('S', WitcheryItems.GOLDEN_THREAD.get())
            .unlockedBy("has_impregnated", has(WitcheryItems.IMPREGNATED_FABRIC.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.BRAZIER.get())
            .pattern("INI")
            .pattern("BBB")
            .define('I', Items.IRON_BARS)
            .define('N', WitcheryItems.NECROMANTIC_STONE.get())
            .define('B', Items.IRON_INGOT)
            .unlockedBy("has_necro", has(WitcheryItems.NECROMANTIC_STONE.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.SUN_COLLECTOR.get())
            .pattern("INI")
            .pattern(" B ")
            .define('I', Items.IRON_BARS)
            .define('N', Items.DAYLIGHT_DETECTOR)
            .define('B', Items.IRON_INGOT)
            .unlockedBy("has_daylight", has(Items.DAYLIGHT_DETECTOR))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.QUARTZ_SPHERE.get())
            .pattern(" Q ")
            .pattern("Q Q")
            .pattern(" Q ")
            .define('Q', Items.QUARTZ)
            .unlockedBy("has_quartz", has(Items.QUARTZ))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.BITING_BELT.get())
            .pattern("LIM")
            .pattern("IFI")
            .pattern("I I")
            .define('I', WitcheryItems.IMPREGNATED_FABRIC.get())
            .define('F', WitcheryItems.FANCIFUL_THREAD.get())
            .define('M', WitcheryItems.MELLIFLUOUS_HUNGER.get())
            .define('L', WitcheryItems.PARASITIC_LOUSE.get())
            .unlockedBy("has_fabric", has(WitcheryItems.IMPREGNATED_FABRIC.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.BARK_BELT.get())
            .pattern("F F")
            .pattern("MBM")
            .pattern("F F")
            .define('M', WitcheryItems.ENT_TWIG.get())
            .define('F', WitcheryItems.BREW_FLOWING_SPIRIT.get())
            .define('B', WitcheryItems.BITING_BELT.get())
            .unlockedBy("has_fabric", has(WitcheryItems.BITING_BELT.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.SCARECROW.get())
            .pattern("WPW")
            .pattern("STS")
            .pattern("WHW")
            .define('T', WitcheryItems.TORMENTED_TWINE.get())
            .define('S', Items.HAY_BLOCK)
            .define('P', Items.CARVED_PUMPKIN)
            .define('H', WitcheryItems.HAWTHORN_LOG.get())
            .define('W', ItemTags.WOOL)
            .unlockedBy("has_twine", has(WitcheryItems.TORMENTED_TWINE.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.CANE_SWORD.get())
            .pattern(" WG")
            .pattern("WSW")
            .pattern("BW ")
            .define('B', Items.GLASS_BOTTLE)
            .define('S', Items.DIAMOND_SWORD)
            .define('W', WitcheryItems.WOVEN_CRUOR.get())
            .define('G', Items.GOLD_INGOT)
            .unlockedBy("has_twine", has(WitcheryItems.WOVEN_CRUOR.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.DREAMWEAVER_CHARM.get())
            .pattern("SSS")
            .pattern("SFS")
            .pattern("SSS")
            .define('S', Items.STICK)
            .define('F', WitcheryItems.FANCIFUL_THREAD.get())
            .unlockedBy("has_stick", has(Items.STICK))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.WEREWOLF_ALTAR.get())
            .pattern(" S ")
            .pattern("SFS")
            .pattern("SOS")
            .define('S', Items.STONE)
            .define('F', WitcheryItems.WOLFSBANE.get())
            .define('O', WitcheryItems.TONGUE_OF_DOG.get())
            .unlockedBy("has_wolfsbane", has(WitcheryItems.WOLFSBANE.get()))
            .save(exporter)

        ShapedRecipeBuilder.shaped(RecipeCategory.MISC, WitcheryItems.COFFIN.get())
            .pattern("SSS")
            .pattern("WBW")
            .pattern("WWW")
            .define('B', ItemTags.BEDS)
            .define('W', ItemTags.LOGS)
            .define('S', ItemTags.WOODEN_SLABS)
            .unlockedBy("has_bed", has(ItemTags.BEDS))
            .save(exporter)

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(Items.NETHERITE_SCRAP, Color(205, 125, 50).rgb)
            .addInputWithColor(WitcheryItems.OIL_OF_VITRIOL.get(), Color(50, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.DEMONS_BLOOD.get(), Color(255, 1, 1).rgb)
            .addOutput(WitcheryItems.PENTACLE.get())
            .setAltarPower(100)
            .unlockedBy("has_oil", has(WitcheryItems.OIL_OF_VITRIOL.get()))
            .save(exporter, Witchery.id("pentacle"))

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(Items.NETHER_WART, Color(255, 55, 50).rgb)
            .addInputWithColor(WitcheryItems.ENT_TWIG.get(), Color(255, 100, 1).rgb)
            .addInputWithColor(WitcheryItems.MUTANDIS_EXTREMIS.get(), Color(255, 1, 1).rgb)
            .addOutput(WitcheryItems.MUTATING_SPRING.get())
            .setAltarPower(100)
            .unlockedBy("has_ent_twig", has(WitcheryItems.ENT_TWIG.get()))
            .save(exporter, Witchery.id("mutating_spring"))

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(100, 50, 50).rgb)
            .addInputWithColor(Items.GOLD_NUGGET, Color(255, 255, 50).rgb)
            .addInputWithColor(WitcheryItems.RITUAL_CHALK.get(), Color(255, 255, 255).rgb)
            .addOutput(WitcheryItems.GOLDEN_CHALK.get())
            .setAltarPower(100)
            .unlockedBy("has_ritual_chalk", has(WitcheryItems.RITUAL_CHALK.get()))
            .save(exporter, Witchery.id("golden_chalk"))

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(Items.NETHER_WART, Color(255, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.TEAR_OF_THE_GODDESS.get(), Color(105, 50, 250).rgb)
            .addInputWithColor(Items.ENDER_PEARL, Color(50, 150, 150).rgb)
            .addInputWithColor(WitcheryItems.RITUAL_CHALK.get(), Color(255, 255, 255).rgb)
            .addOutput(WitcheryItems.OTHERWHERE_CHALK.get())
            .setAltarPower(100)
            .unlockedBy("has_ritual_chalk", has(WitcheryItems.RITUAL_CHALK.get()))
            .save(exporter, Witchery.id("otherwhere_chalk"))

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(Items.NETHER_WART, Color(255, 50, 50).rgb)
            .addInputWithColor(Items.BLAZE_POWDER, Color(205, 200, 10).rgb)
            .addInputWithColor(WitcheryItems.RITUAL_CHALK.get(), Color(200, 200, 200).rgb)
            .addOutput(WitcheryItems.INFERNAL_CHALK.get())
            .setAltarPower(100)
            .unlockedBy("has_ritual_chalk", has(WitcheryItems.RITUAL_CHALK.get()))
            .save(exporter, Witchery.id("infernal_chalk"))

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(100, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.EXHALE_OF_THE_HORNED_ONE.get(), Color(100, 150, 50).rgb)
            .addInputWithColor(Items.EGG, Color(150, 150, 50).rgb)
            .addOutput(WitcheryItems.MUTANDIS.get(), 4)
            .setAltarPower(100)
            .unlockedBy("has_ritual_chalk", has(WitcheryItems.MANDRAKE_ROOT.get()))
            .save(exporter, Witchery.id("mutandis"))

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(Items.NETHER_WART, Color(255, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.MUTANDIS.get(), Color(155, 150, 50).rgb)
            .addOutput(WitcheryItems.MUTANDIS_EXTREMIS.get())
            .setAltarPower(100)
            .unlockedBy("has_ritual_chalk", has(WitcheryItems.RITUAL_CHALK.get()))
            .save(exporter, Witchery.id("mutandis_extremis"))

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(100, 50, 50).rgb)
            .addInputWithColor(Items.NETHER_WART, Color(255, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.TEAR_OF_THE_GODDESS.get(), Color(55, 50, 250).rgb)
            .addInputWithColor(WitcheryItems.REFINED_EVIL.get(), Color(20, 20, 20).rgb)
            .addInputWithColor(WitcheryItems.MUTANDIS_EXTREMIS.get(), Color(50, 20, 20).rgb)
            .addOutput(WitcheryItems.DROP_OF_LUCK.get())
            .setAltarPower(100)
            .unlockedBy("has_refined_evil", has(WitcheryItems.REFINED_EVIL.get()))
            .save(exporter, Witchery.id("drop_of_luck"))

        CauldronCraftingRecipeBuilder.create()
            .addInputWithColor(WitcheryItems.MANDRAKE_ROOT.get(), Color(100, 50, 50).rgb)
            .addInputWithColor(WitcheryItems.TEAR_OF_THE_GODDESS.get(), Color(100, 150, 150).rgb)
            .addInputWithColor(WitcheryItems.PHANTOM_VAPOR.get(), Color(150, 150, 150).rgb)
            .addInputWithColor(Items.ENDER_PEARL, Color(50, 150, 150).rgb)
            .addInputWithColor(Items.WHEAT, Color(150, 150, 50).rgb)
            .addInputWithColor(WitcheryItems.MUTANDIS.get(), Color(150, 190, 50).rgb)
            .addOutput(Items.NETHER_WART, 1)
            .setAltarPower(100)
            .unlockedBy("has_ritual_chalk", has(WitcheryItems.MANDRAKE_ROOT.get()))
            .save(exporter, Witchery.id("nether_wart"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(Items.OAK_SAPLING))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.EXHALE_OF_THE_HORNED_ONE.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("exhale_of_the_horned_one"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(Items.DARK_OAK_SAPLING))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.EXHALE_OF_THE_HORNED_ONE.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("exhale_of_the_horned_one2"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(Items.BIRCH_SAPLING))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.BREATH_OF_THE_GODDESS.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("breath_of_the_goddess"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(Items.CHERRY_SAPLING))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.BREATH_OF_THE_GODDESS.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("breath_of_the_goddess2"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(Items.SPRUCE_SAPLING))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.HINT_OF_REBIRTH.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("hint_of_rebirth"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(Items.JUNGLE_SAPLING))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.HINT_OF_REBIRTH.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("hint_of_rebirth2"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(WitcheryItems.ROWAN_SAPLING.get()))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.WHIFF_OF_MAGIC.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("whiff_of_magic"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(WitcheryItems.ALDER_SAPLING.get()))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.REEK_OF_MISFORTUNE.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("reek_of_misfortune"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(WitcheryItems.HAWTHORN_SAPLING.get()))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.ODOR_OF_PURITY.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("odor_of_purity"))

        OvenCookingRecipeBuilder.create()
            .addIngredient(Ingredient.of(ItemTags.LOGS))
            .addExtraIngredient(Ingredient.of(WitcheryItems.JAR.get()))
            .addResult(WitcheryItems.WOOD_ASH.get())
            .addExtraOutput(WitcheryItems.FOUL_FUME.get(), 0.5f)
            .setExperience(0.5f)
            .setCookingTime(85)
            .save(exporter, Witchery.id("foul_fume_logs"))


        RitualRecipeBuilder.create()
            .addInputItem(Items.ENDER_PEARL)
            .addInputItem(WitcheryItems.REFINED_EVIL.get())
            .addInputItem(WitcheryItems.DEMONS_BLOOD.get())
            .addInputItem(WitcheryItems.PHANTOM_VAPOR.get())
            .addOutputEntity(WitcheryEntityTypes.IMP.get())
            .setTicks(20 * 5)
            .setAltarPower(5000)
            .addMediumPattern(WitcheryBlocks.INFERNAL_CHALK_BLOCK.get())
            .save(exporter, Witchery.id("summon_imp"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.ENDER_DEW.get())
            .addInputItem(WitcheryItems.WAYSTONE.get())
            .addInputItem(WitcheryItems.TAGLOCK.get())
            .addInputItem(Items.IRON_INGOT)
            .addCommand(CommandType("tp {taglockPlayerOrEntity} {waystonePos}", CommandType.END))
            .setTicks(20 * 2)
            .setAltarPower(3000)
            .addMediumPattern(WitcheryBlocks.OTHERWHERE_CHALK_BLOCK.get())
            .save(exporter, Witchery.id("teleport_taglock_to_waystone"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.ATTUNED_STONE.get())
            .addInputItem(Items.BONE)
            .addInputItem(Items.ROTTEN_FLESH)
            .addInputItem(WitcheryItems.WOOD_ASH.get())
            .addInputItem(WitcheryItems.SPECTRAL_DUST.get())
            .addOutputItem(WitcheryItems.NECROMANTIC_STONE.get())
            .setAltarPower(1000)
            .addSmallPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .setCelestialConditions(setOf(RitualRecipe.Celestial.NIGHT))
            .save(exporter, Witchery.id("necro_stone"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.WAYSTONE.get())
            .addCommand(CommandType("tp {owner} {waystonePos}", CommandType.END))
            .setTicks(20)
            .addSmallPattern(WitcheryBlocks.OTHERWHERE_CHALK_BLOCK.get())
            .save(exporter, Witchery.id("teleport_owner_to_waystone"))

        RitualRecipeBuilder.create()
            .addInputItem(Items.COPPER_INGOT)
            .addInputItem(WitcheryItems.WOOD_ASH.get())
            .setAltarPower(1000)
            .setTicks(20)
            .addSmallPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .addCommand(CommandType("summon lightning_bolt {chalkPos}", CommandType.END))
            .save(exporter, Witchery.id("summon_lightning"))

        RitualRecipeBuilder.create()
            .addInputItem(Items.COPPER_INGOT)
            .addInputItem(WitcheryItems.WOOD_ASH.get())
            .addInputItem(WitcheryItems.WAYSTONE.get())
            .setAltarPower(2000)
            .setTicks(20)
            .addSmallPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .addCommand(CommandType("summon lightning_bolt {waystonePos}", CommandType.END))
            .save(exporter, Witchery.id("summon_lightning_on_waystone"))

        RitualRecipeBuilder.create()
            .addInputItem(Items.WOODEN_AXE)
            .addInputItem(WitcheryItems.WOOD_ASH.get())
            .setAltarPower(3000)
            .setTicks(20)
            .addCommand(CommandType("time set midnight", CommandType.END))
            .addSmallPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .save(exporter, Witchery.id("set_midnight"))

        RitualRecipeBuilder.create()
            .addInputItem(Items.FEATHER)
            .addInputItem(Items.REDSTONE)
            .setAltarPower(20)
            .setInfinite(true)
            .addSmallPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .setCustomRitual(PushMobsRitual())
            .save(exporter, Witchery.id("push_mobs"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.TEAR_OF_THE_GODDESS.get())
            .addInputItem(WitcheryItems.ODOR_OF_PURITY.get())
            .addInputItem(WitcheryItems.WHIFF_OF_MAGIC.get())
            .addInputItem(Items.DIAMOND)
            .addInputItem(WitcheryItems.DEMONS_BLOOD.get())
            .addMediumPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .setAltarPower(8000)
            .setTicks(20)
            .setCustomRitual(BindFamiliarRitual())
            .save(exporter, Witchery.id("bind_familiar"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.BREATH_OF_THE_GODDESS.get())
            .addInputItem(WitcheryItems.HINT_OF_REBIRTH.get())
            .addInputItem(WitcheryItems.WHIFF_OF_MAGIC.get())
            .addMediumPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .setAltarPower(1000)
            .setTicks(20)
            .setCustomRitual(ResurrectFamiliarRitual())
            .save(exporter, Witchery.id("resurrect_familiar"))

        val attuned = ItemStack(WitcheryItems.ATTUNED_STONE.get())
        attuned.set(WitcheryDataComponents.ATTUNED.get(), true)

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.ATTUNED_STONE.get())
            .addInputItem(Items.REDSTONE)
            .addInputItem(Items.GLOWSTONE_DUST)
            .addInputItem(WitcheryItems.WOOD_ASH.get())
            .addOutputItem(attuned)
            .setAltarPower(2500)
            .addSmallPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .save(exporter, Witchery.id("charge_attuned"))

        val broom = ItemStack(WitcheryItems.BROOM.get())
        broom.set(WitcheryDataComponents.HAS_OINTMENT.get(), true)

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.FLYING_OINTMENT.get())
            .addInputItem(WitcheryItems.BROOM.get())
            .addOutputItem(broom)
            .setAltarPower(3000)
            .addSmallAndMediumPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get(), WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .save(exporter, Witchery.id("apply_ointment"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.GHOST_OF_THE_LIGHT.get())
            .setAltarPower(2000)
            .addCommand(CommandType("witchery infusion setAndKill {owner} light", CommandType.END))
            .addSmallAndMediumPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get(), WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .save(exporter, Witchery.id("infuse_light"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.SPIRIT_OF_OTHERWHERE.get())
            .setAltarPower(2000)
            .addCommand(CommandType("witchery infusion setAndKill {owner} otherwhere", CommandType.END))
            .addSmallAndMediumPattern(
                WitcheryBlocks.OTHERWHERE_CHALK_BLOCK.get(),
                WitcheryBlocks.OTHERWHERE_CHALK_BLOCK.get()
            )
            .save(exporter, Witchery.id("infuse_otherwhere"))

        RitualRecipeBuilder.create()
            .addInputItem(PotionContents.createItemStack(Items.POTION, Potions.STRONG_REGENERATION))
            .setAltarPower(40)
            .addCommand(CommandType("witchery infusion increase {owner} 1", CommandType.TICK))
            .setInfinite(true)
            .addSmallAndMediumPattern(
                WitcheryBlocks.RITUAL_CHALK_BLOCK.get(),
                WitcheryBlocks.OTHERWHERE_CHALK_BLOCK.get()
            )
            .save(exporter, Witchery.id("rite_of_charging_infusion"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.DROP_OF_LUCK.get())
            .addInputItem(Items.PORKCHOP)
            .addInputItem(Items.GOLD_INGOT)
            .addInputItem(WitcheryItems.ARTHANA.get())
            .setAltarPower(2000)
            .addSmallPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .addOutputEntity(WitcheryEntityTypes.SPECTRAL_PIG.get())
            .save(exporter, Witchery.id("summon_spectral_pig"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.REFINED_EVIL.get())
            .addInputItem(Items.BLAZE_POWDER)
            .addInputItem(Items.ENDER_PEARL)
            .addInputEntity(EntityType.VILLAGER)
            .setAltarPower(3000)
            .addLargePattern(WitcheryBlocks.INFERNAL_CHALK_BLOCK.get())
            .addOutputEntity(WitcheryEntityTypes.DEMON.get())
            .save(exporter, Witchery.id("summon_demon"))

        RitualRecipeBuilder.create()
            .addInputItem(Items.WITHER_SKELETON_SKULL)
            .addInputItem(WitcheryItems.PHANTOM_VAPOR.get())
            .addInputItem(Items.ENDER_PEARL)
            .addInputEntity(EntityType.VILLAGER)
            .setAltarPower(4000)
            .addMediumAndLargePattern(
                WitcheryBlocks.INFERNAL_CHALK_BLOCK.get(),
                WitcheryBlocks.INFERNAL_CHALK_BLOCK.get()
            )
            .addOutputEntity(EntityType.WITHER)
            .save(exporter, Witchery.id("summon_wither"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.PHANTOM_VAPOR.get())
            .addInputItem(WitcheryItems.EXHALE_OF_THE_HORNED_ONE.get())
            .addInputItem(Items.MAGMA_CREAM)
            .addInputItem(WitcheryItems.ARTHANA.get())
            .addInputItem(Items.FERMENTED_SPIDER_EYE)
            .setAltarPower(2000)
            .addSmallPattern(WitcheryBlocks.INFERNAL_CHALK_BLOCK.get())
            .addOutputEntity(EntityType.WITCH)
            .save(exporter, Witchery.id("summon_witch"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.SPECTRAL_DUST.get())
            .addInputItem(WitcheryItems.MELLIFLUOUS_HUNGER.get())
            .addInputItem(WitcheryItems.NECROMANTIC_STONE.get())
            .addInputItem(WitcheryItems.ARTHANA.get())
            .addInputItem(Items.GUNPOWDER)
            .setAltarPower(5000)
            .addCommand(CommandType("witchery manifestation set {owner} true", CommandType.END))
            .addSmallPattern(WitcheryBlocks.OTHERWHERE_CHALK_BLOCK.get())
            .save(exporter, Witchery.id("manifestation"))

        RitualRecipeBuilder.create()
            .addInputItem(WitcheryItems.ATTUNED_STONE.get())
            .addInputItem(WitcheryItems.NECROMANTIC_STONE.get())
            .addInputItem(WitcheryItems.ARTHANA.get())
            .setAltarPower(6000)
            .addMediumPattern(WitcheryBlocks.RITUAL_CHALK_BLOCK.get())
            .setCustomRitual(BindSpectralCreaturesRitual())
            .setTicks(20)
            .save(exporter, Witchery.id("bind_spectral_creatures"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(WitcheryItems.FOUL_FUME.get())
            .addInput(WitcheryItems.WOOD_ASH.get())
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.OIL_OF_VITRIOL.get())
            .addOutput(WitcheryItems.GYPSUM.get())
            .addOutput(Items.SLIME_BALL)
            .setJarConsumption(1)
            .save(exporter, Witchery.id("oil_of_vitriol_gypsum"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(WitcheryItems.BREATH_OF_THE_GODDESS.get())
            .addInput(Items.LAPIS_LAZULI)
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.TEAR_OF_THE_GODDESS.get())
            .addOutput(WitcheryItems.WHIFF_OF_MAGIC.get())
            .addOutput(Items.SLIME_BALL)
            .addOutput(WitcheryItems.FOUL_FUME.get())
            .setJarConsumption(3)
            .save(exporter, Witchery.id("tear_and_whiff"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(Items.ENDER_PEARL)
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.ENDER_DEW.get(), 2)
            .addOutput(WitcheryItems.ENDER_DEW.get(), 2)
            .addOutput(WitcheryItems.ENDER_DEW.get(), 1)
            .addOutput(WitcheryItems.WHIFF_OF_MAGIC.get())
            .setJarConsumption(6)
            .save(exporter, Witchery.id("ender_dew"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(Items.BLAZE_POWDER)
            .addInput(Items.GUNPOWDER)
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.REEK_OF_MISFORTUNE.get())
            .addOutput(Items.GLOWSTONE_DUST)
            .addOutput(Items.GLOWSTONE_DUST)
            .setJarConsumption(1)
            .save(exporter, Witchery.id("reek_of_misfortune_glowstone"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(Items.PHANTOM_MEMBRANE)
            .addInput(WitcheryItems.OIL_OF_VITRIOL.get())
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.PHANTOM_VAPOR.get(), 1)
            .addOutput(WitcheryItems.PHANTOM_VAPOR.get(), 1)
            .addOutput(WitcheryItems.ODOR_OF_PURITY.get())
            .setJarConsumption(3)
            .save(exporter, Witchery.id("phantom_vapor"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(WitcheryItems.DEMON_HEART.get())
            .addInput(WitcheryItems.PHANTOM_VAPOR.get())
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.DEMONS_BLOOD.get(), 2)
            .addOutput(WitcheryItems.DEMONS_BLOOD.get(), 2)
            .addOutput(WitcheryItems.REFINED_EVIL.get())
            .setJarConsumption(4)
            .save(exporter, Witchery.id("refined_evil"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(WitcheryItems.DEMON_HEART.get())
            .addInput(Items.NETHERRACK)
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.DEMONS_BLOOD.get())
            .addOutput(WitcheryItems.DEMONS_BLOOD.get())
            .addOutput(Items.SOUL_SAND)
            .setJarConsumption(2)
            .save(exporter, Witchery.id("demons_blood"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(WitcheryItems.PHANTOM_VAPOR.get())
            .addInput(Items.GHAST_TEAR)
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.ODOR_OF_PURITY.get())
            .addOutput(WitcheryItems.REEK_OF_MISFORTUNE.get())
            .addOutput(WitcheryItems.FOUL_FUME.get())
            .addOutput(WitcheryItems.REFINED_EVIL.get())
            .setJarConsumption(3)
            .save(exporter, Witchery.id("refined_evil_from_ghast"))

        DistilleryCraftingRecipeBuilder.create()
            .addInput(WitcheryItems.BREW_FLOWING_SPIRIT.get())
            .addInput(WitcheryItems.OIL_OF_VITRIOL.get())
            .setAltarPower(5)
            .setCookingTime(100)
            .addOutput(WitcheryItems.FOCUSED_WILL.get())
            .addOutput(WitcheryItems.CONDENSED_FEAR.get())
            //TODO .addOutput(ItemStack(WitcheryItems.BREW_OF_HOLLOW_TEARS.get(), 4))
            //TODO .addOutput(ItemStack(WitcheryItems.BREW_OF_HOLLOW_TEARS.get(), 4))
            .setJarConsumption(2)
            .save(exporter, Witchery.id("brew_of_hollow_tears"))

        BrazierSummoningRecipeBuilder.create()
            .addInput(WitcheryItems.WORMWOOD.get())
            .addInput(WitcheryItems.CONDENSED_FEAR.get())
            .addInput(WitcheryItems.SPECTRAL_DUST.get())
            .setAltarPower(500)
            .addSummon(WitcheryEntityTypes.BANSHEE.get())
            .save(exporter, Witchery.id("summon_banshee"))

        BrazierSummoningRecipeBuilder.create()
            .addInput(WitcheryItems.WORMWOOD.get())
            .addInput(WitcheryItems.WOOL_OF_BAT.get())
            .addInput(WitcheryItems.SPECTRAL_DUST.get())
            .setAltarPower(500)
            .addSummon(WitcheryEntityTypes.SPECTRE.get())
            .save(exporter, Witchery.id("summon_spectre"))


        SimpleCookingRecipeBuilder.smelting(
            Ingredient.of(WitcheryItems.BLOOD_STAINED_WOOL.get()),
            RecipeCategory.MISC,
            WitcheryItems.WOVEN_CRUOR.get(),
            0.35f, 200
        )
            .unlockedBy("has_blood", has(WitcheryItems.BLOOD_STAINED_WOOL.get()))
            .save(exporter, Witchery.id("woven_cruor"))
    }
}