package dev.sterner.witchery.fabric.datagen

import dev.sterner.witchery.registry.WitcheryBlocks
import dev.sterner.witchery.registry.WitcheryEntityTypes
import dev.sterner.witchery.registry.WitcheryItems
import dev.sterner.witchery.registry.WitcheryTags
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider
import net.minecraft.core.HolderLookup
import java.util.concurrent.CompletableFuture

class WitcheryLangProvider(dataOutput: FabricDataOutput, registryLookup: CompletableFuture<HolderLookup.Provider>) :
    FabricLanguageProvider(dataOutput, registryLookup) {

    override fun generateTranslations(registryLookup: HolderLookup.Provider?, builder: TranslationBuilder) {
        builder.add("witchery.main", "Witchery")

        builder.add("emi.category.witchery.cauldron_brewing", "Cauldron Brewing")
        builder.add("emi.category.witchery.cauldron_crafting", "Cauldron Crafting")
        builder.add("emi.category.witchery.ritual", "Ritual")
        builder.add("emi.category.witchery.oven_cooking", "Oven Fumigation")
        builder.add("emi.category.witchery.distilling", "Distilling")
        builder.add("emi.category.witchery.spinning", "Spinning")
        builder.add("container.witchery.oven_menu", "Witches Oven")
        builder.add("container.witchery.altar_menu", "Altar")
        builder.add("container.witchery.spinning_wheel", "Spinning Wheel")
        builder.add("container.witchery.distillery", "Distillery")

        builder.add("witchery.secondbrewbonus.25", "+25% chance of second brew")
        builder.add("witchery.secondbrewbonus.35", "+35% chance of second brew")
        builder.add("witchery.thirdbrewbonus.25", "+25% chance of third brew")
        builder.add("witchery.infusion.ointment", "Flying Ointment")


        builder.add( "witchery.item.tooltip.infinity_egg", "Creative Only")

        builder.add(WitcheryItems.INFINITY_EGG.get(), "Infinity Egg")
        builder.add(WitcheryItems.DEEPSLATE_ALTAR_BLOCK.get(), "Deepslate Altar Block")
        builder.add(WitcheryItems.DISTILLERY.get(), "Distillery")
        builder.add(WitcheryItems.SPINNING_WHEEL.get(), "Spinning Wheel")
        builder.add(WitcheryItems.GUIDEBOOK.get(), "Lesser Key of Solomon")
        builder.add(WitcheryItems.CAULDRON.get(), "Cauldron")
        builder.add(WitcheryItems.COPPER_CAULDRON.get(), "Copper Cauldron")

        builder.add(WitcheryItems.WAXED_COPPER_CAULDRON.get(), "Waxed Copper Cauldron")
        builder.add(WitcheryItems.EXPOSED_COPPER_CAULDRON.get(), "Exposed Copper Cauldron")
        builder.add(WitcheryItems.WAXED_EXPOSED_COPPER_CAULDRON.get(), "Waxed Exposed Copper Cauldron")
        builder.add(WitcheryItems.WEATHERED_COPPER_CAULDRON.get(), "Weathered Copper Cauldron")
        builder.add(WitcheryItems.WAXED_WEATHERED_COPPER_CAULDRON.get(), "Waxed Weathered Copper Cauldron")
        builder.add(WitcheryItems.OXIDIZED_COPPER_CAULDRON.get(), "Oxidized Copper Cauldron")
        builder.add(WitcheryItems.WAXED_OXIDIZED_COPPER_CAULDRON.get(), "Waxed Oxidized Copper Cauldron")

        builder.add(WitcheryItems.ALTAR.get(), "Altar")
        builder.add(WitcheryItems.MUTANDIS.get(), "Mutandis")
        builder.add(WitcheryItems.MUTANDIS_EXTREMIS.get(), "Mutandis Extremis")
        builder.add(WitcheryItems.MANDRAKE_ROOT.get(), "Mandrake Root")
        builder.add(WitcheryItems.GYPSUM.get(), "Gypsum")
        builder.add(WitcheryItems.WOOD_ASH.get(), "Wood Ash")
        builder.add(WitcheryItems.BELLADONNA_FLOWER.get(), "Belladonna Flower")
        builder.add(WitcheryItems.WATER_ARTICHOKE_GLOBE.get(), "Water Artichoke Globe")
        builder.add(WitcheryItems.BONE_NEEDLE.get(), "Bone Needle")
        builder.add(WitcheryItems.DEMON_HEART.get(), "Demon Heart")
        builder.add(WitcheryItems.RITUAL_CHALK.get(), "Ritual Chalk")
        builder.add(WitcheryItems.INFERNAL_CHALK.get(), "Infernal Chalk")
        builder.add(WitcheryItems.OTHERWHERE_CHALK.get(), "Otherwhere Chalk")
        builder.add(WitcheryItems.GOLDEN_CHALK.get(), "Golden Chalk")
        builder.add(WitcheryItems.ICY_NEEDLE.get(), "Icy Needle")
        builder.add(WitcheryItems.BELLADONNA_SEEDS.get(), "Belladonna Seeds")
        builder.add(WitcheryItems.MANDRAKE_SEEDS.get(), "Mandrake Seeds")
        builder.add(WitcheryItems.SNOWBELL_SEEDS.get(), "Snowbell Seeds")
        builder.add(WitcheryItems.WATER_ARTICHOKE_SEEDS.get(), "Water Artichoke Seeds")
        builder.add(WitcheryItems.WORMWOOD.get(), "Wormwood")
        builder.add(WitcheryItems.WORMWOOD_SEEDS.get(), "Wormwood Seeds")
        builder.add(WitcheryItems.WOLFSBANE.get(), "Wolfsbane")
        builder.add(WitcheryItems.GARLIC.get(), "Garlic")
        builder.add(WitcheryItems.WOLFSBANE_SEEDS.get(), "Wolfsbane Seeds")
        builder.add(WitcheryItems.TAGLOCK.get(), "Taglock")
        builder.add(WitcheryItems.REFINED_EVIL.get(), "Refined Evil")
        builder.add(WitcheryItems.REDSTONE_SOUP.get(), "Redstone Soup")
        builder.add(WitcheryItems.FLYING_OINTMENT.get(), "Flying Ointment")
        builder.add(WitcheryItems.SOUL_OF_THE_WORLD.get(), "Soul of the Overworld")
        builder.add(WitcheryItems.SPIRIT_OF_OTHERWHERE.get(), "Spirit of Otherwhere")
        builder.add(WitcheryItems.GHOST_OF_THE_LIGHT.get(), "Ghost of the Light")
        builder.add(WitcheryItems.INFERNAL_ANIMUS.get(), "Infernal Animus")
        builder.add(WitcheryItems.TONGUE_OF_DOG.get(), "Tongue of Dog")
        builder.add(WitcheryItems.WOOL_OF_BAT.get(), "Wool of Bat")
        builder.add(WitcheryItems.TOE_OF_FROG.get(), "Toe of Frog")
        builder.add(WitcheryItems.OWLETS_WING.get(), "Owlet's Wing")
        builder.add(WitcheryItems.ENT_TWIG.get(), "Ent Twig")
        builder.add(WitcheryItems.ATTUNED_STONE.get(), "Attuned Stone")
        builder.add(WitcheryItems.ROWAN_BERRIES.get(), "Rowan Berries")
        builder.add(WitcheryItems.WITCHES_HAND.get(), "Witches Hand")
        builder.add(WitcheryItems.WITCHES_HAT.get(), "Witches Hat")
        builder.add(WitcheryItems.WITCHES_ROBES.get(), "Witches Robes")
        builder.add(WitcheryItems.WITCHES_SLIPPERS.get(), "Witches Slippers")
        builder.add(WitcheryItems.GOLDEN_THREAD.get(), "Golden Thread")
        builder.add(WitcheryItems.POPPET.get(), "Poppet")
        builder.add(WitcheryItems.ARMOR_PROTECTION_POPPET.get(), "Armor Protection Poppet")
        builder.add(WitcheryItems.HUNGER_PROTECTION_POPPET.get(), "Hunger Protection Poppet")
        builder.add(WitcheryItems.DEATH_PROTECTION_POPPET.get(), "Death Protection Poppet")
        builder.add(WitcheryItems.VAMPIRIC_POPPET.get(), "Vampiric Poppet")
        builder.add(WitcheryItems.VOODOO_POPPET.get(), "Voodoo Poppet")
        builder.add(WitcheryItems.VOODOO_PROTECTION_POPPET.get(), "Voodoo Protection Poppet")
        builder.add(WitcheryItems.BABA_YAGAS_HAT.get(), "Baba Yaga's Hat")
        builder.add(WitcheryItems.IMPREGNATED_FABRIC.get(), "Impregnated Fabric")
        builder.add(WitcheryItems.MUTATING_SPRING.get(), "Mutating Spring")
        builder.add(WitcheryItems.BROOM.get(), "Broom")
        builder.add(WitcheryEntityTypes.BROOM.get(), "Broom")

        builder.add(WitcheryBlocks.GLINTWEED.get(), "Glintweed")
        builder.add(WitcheryBlocks.EMBER_MOSS.get(), "Ember Moss")
        builder.add(WitcheryBlocks.SPANISH_MOSS.get(), "Spanish Moss")
        builder.add(WitcheryBlocks.IRON_WITCHES_OVEN.get(), "Iron Witches Oven")
        builder.add(WitcheryBlocks.IRON_WITCHES_OVEN_FUME_EXTENSION.get(), "Iron Witches Oven Fume Filter")
        builder.add(WitcheryBlocks.COPPER_WITCHES_OVEN.get(), "Copper Witches Oven")
        builder.add(WitcheryBlocks.EXPOSED_COPPER_WITCHES_OVEN.get(), "Exposed Copper Witches Oven")
        builder.add(WitcheryBlocks.WEATHERED_COPPER_WITCHES_OVEN.get(), "Weathered Copper Witches Oven")
        builder.add(WitcheryBlocks.OXIDIZED_COPPER_WITCHES_OVEN.get(), "Oxidized Copper Witches Oven")
        builder.add(WitcheryBlocks.WAXED_COPPER_WITCHES_OVEN.get(), "Waxed Copper Witches Oven")
        builder.add(WitcheryBlocks.WAXED_EXPOSED_COPPER_WITCHES_OVEN.get(), "Waxed Exposed Copper Witches Oven")
        builder.add(WitcheryBlocks.WAXED_WEATHERED_COPPER_WITCHES_OVEN.get(), "Waxed Weathered Copper Witches Oven")
        builder.add(WitcheryBlocks.WAXED_OXIDIZED_COPPER_WITCHES_OVEN.get(), "Waxed Oxidized Copper Witches Oven")
        builder.add(WitcheryBlocks.COPPER_WITCHES_OVEN_FUME_EXTENSION.get(), "Copper Witches Oven Fume Filter")
        builder.add(WitcheryBlocks.WAXED_COPPER_WITCHES_OVEN_FUME_EXTENSION.get(), "Waxed Copper Witches Oven Fume Filter")
        builder.add(WitcheryBlocks.EXPOSED_COPPER_WITCHES_OVEN_FUME_EXTENSION.get(), "Exposed Copper Witches Oven Fume Filter")
        builder.add(WitcheryBlocks.WAXED_EXPOSED_COPPER_WITCHES_OVEN_FUME_EXTENSION.get(), "Waxed Exposed Copper Witches Oven Fume Filter")
        builder.add(WitcheryBlocks.WEATHERED_COPPER_WITCHES_OVEN_FUME_EXTENSION.get(), "Weathered Copper Witches Oven Fume Filter")
        builder.add(WitcheryBlocks.WAXED_WEATHERED_COPPER_WITCHES_OVEN_FUME_EXTENSION.get(), "Waxed Weathered Copper Witches Oven Fume Filter")
        builder.add(WitcheryBlocks.OXIDIZED_COPPER_WITCHES_OVEN_FUME_EXTENSION.get(), "Oxidized Copper Witches Oven Fume Filter")
        builder.add(WitcheryBlocks.WAXED_OXIDIZED_COPPER_WITCHES_OVEN_FUME_EXTENSION.get(), "Waxed Oxidized Copper Witches Oven Fume Filter")

        builder.add(WitcheryBlocks.IRON_CANDELABRA.get(), "Iron Candelabra")
        builder.add(WitcheryBlocks.WHITE_IRON_CANDELABRA.get(), "White Iron Candelabra")
        builder.add(WitcheryBlocks.ORANGE_IRON_CANDELABRA.get(), "Orange Iron Candelabra")
        builder.add(WitcheryBlocks.MAGENTA_IRON_CANDELABRA.get(), "Magenta Iron Candelabra")
        builder.add(WitcheryBlocks.LIGHT_BLUE_IRON_CANDELABRA.get(), "Light Blue Iron Candelabra")
        builder.add(WitcheryBlocks.YELLOW_IRON_CANDELABRA.get(), "Yellow Iron Candelabra")
        builder.add(WitcheryBlocks.LIME_IRON_CANDELABRA.get(), "Lime Iron Candelabra")
        builder.add(WitcheryBlocks.PINK_IRON_CANDELABRA.get(), "Pink Iron Candelabra")
        builder.add(WitcheryBlocks.GRAY_IRON_CANDELABRA.get(), "Gray Iron Candelabra")
        builder.add(WitcheryBlocks.LIGHT_GRAY_IRON_CANDELABRA.get(), "Light Gray Iron Candelabra")
        builder.add(WitcheryBlocks.CYAN_IRON_CANDELABRA.get(), "Cyan Iron Candelabra")
        builder.add(WitcheryBlocks.PURPLE_IRON_CANDELABRA.get(), "Purple Iron Candelabra")
        builder.add(WitcheryBlocks.BLUE_IRON_CANDELABRA.get(), "Blue Iron Candelabra")
        builder.add(WitcheryBlocks.BROWN_IRON_CANDELABRA.get(), "Brown Iron Candelabra")
        builder.add(WitcheryBlocks.GREEN_IRON_CANDELABRA.get(), "Green Iron Candelabra")
        builder.add(WitcheryBlocks.RED_IRON_CANDELABRA.get(), "Red Iron Candelabra")
        builder.add(WitcheryBlocks.BLACK_IRON_CANDELABRA.get(), "Black Iron Candelabra")
        builder.add(WitcheryBlocks.ARTHANA.get(), "Arthana")
        builder.add(WitcheryItems.ARTHANA.get(), "Arthana")
        builder.add(WitcheryBlocks.CHALICE.get(), "Chalice")
        builder.add(WitcheryBlocks.PENTACLE.get(), "Pentacle")


        builder.add(WitcheryBlocks.GOLDEN_CHALK_BLOCK.get(), "Golden Chalk")
        builder.add(WitcheryBlocks.RITUAL_CHALK_BLOCK.get(), "Ritual Chalk")
        builder.add(WitcheryBlocks.INFERNAL_CHALK_BLOCK.get(), "Infernal Chalk")
        builder.add(WitcheryBlocks.OTHERWHERE_CHALK_BLOCK.get(), "Otherwhere Chalk")
        builder.add(WitcheryBlocks.DEMON_HEART.get(), "Demon Heart")
        builder.add(WitcheryBlocks.ALTAR_COMPONENT.get(), "Altar")
        builder.add(WitcheryBlocks.CAULDRON_COMPONENT.get(), "Cauldron")
        builder.add(WitcheryBlocks.DISTILLERY_COMPONENT.get(), "Distillery")
        builder.add(WitcheryBlocks.IRON_WITCHES_OVEN_FUME_EXTENSION_COMPONENT.get(), "Fume Filter")

        builder.add(WitcheryItems.WAYSTONE.get(), "Waystone")
        builder.add(WitcheryItems.CLAY_JAR.get(), "Clay Jar")
        builder.add(WitcheryItems.JAR.get(), "Jar")
        builder.add(WitcheryItems.BREATH_OF_THE_GODDESS.get(), "Breath of the Goddess")
        builder.add(WitcheryItems.WHIFF_OF_MAGIC.get(), "Whiff of Magic")
        builder.add(WitcheryItems.FOUL_FUME.get(), "Foul Fume")
        builder.add(WitcheryItems.TEAR_OF_THE_GODDESS.get(), "Tear of the Goddess")
        builder.add(WitcheryItems.OIL_OF_VITRIOL.get(), "Oil of Vitriol")
        builder.add(WitcheryItems.EXHALE_OF_THE_HORNED_ONE.get(), "Exhale of the Horned One")
        builder.add(WitcheryItems.HINT_OF_REBIRTH.get(), "Hint of Rebirth")
        builder.add(WitcheryItems.REEK_OF_MISFORTUNE.get(), "Reek of Misfortune")
        builder.add(WitcheryItems.ODOR_OF_PURITY.get(), "Odor of Purity")
        builder.add(WitcheryItems.DROP_OF_LUCK.get(), "Drop of Luck")
        builder.add(WitcheryItems.ENDER_DEW.get(), "Ender Dew")
        builder.add(WitcheryItems.DEMONS_BLOOD.get(), "Demon Blood")
        builder.add(WitcheryItems.FOCUSED_WILL.get(), "Focused Will")
        builder.add(WitcheryItems.CONDENSED_FEAR.get(), "Condensed Fear")
        builder.add(WitcheryItems.MELLIFLUOUS_HUNGER.get(), "Mellifluous Hunger")
        builder.add(WitcheryItems.PHANTOM_VAPOR.get(), "Phantom Vapor")

        builder.add(WitcheryBlocks.ROWAN_LOG.get(), "Rowan Log")
        builder.add(WitcheryBlocks.ROWAN_WOOD.get(), "Rowan Wood")
        builder.add(WitcheryBlocks.STRIPPED_ROWAN_LOG.get(), "Stripped Rowan Log")
        builder.add(WitcheryBlocks.STRIPPED_ROWAN_WOOD.get(), "Stripped Rowan Wood")
        builder.add(WitcheryBlocks.ROWAN_LEAVES.get(), "Rowan Leaves")
        builder.add(WitcheryBlocks.ROWAN_BERRY_LEAVES.get(), "Rowan Berry Leaves")
        builder.add(WitcheryBlocks.ROWAN_PLANKS.get(), "Rowan Planks")
        builder.add(WitcheryBlocks.ROWAN_STAIRS.get(), "Rowan Stairs")
        builder.add(WitcheryBlocks.ROWAN_SLAB.get(), "Rowan Slab")
        builder.add(WitcheryBlocks.ROWAN_FENCE.get(), "Rowan Fence")
        builder.add(WitcheryBlocks.ROWAN_FENCE_GATE.get(), "Rowan Fence Gate")
        builder.add(WitcheryBlocks.ROWAN_DOOR.get(), "Rowan Door")
        builder.add(WitcheryBlocks.ROWAN_TRAPDOOR.get(), "Rowan Trapdoor")
        builder.add(WitcheryBlocks.ROWAN_PRESSURE_PLATE.get(), "Rowan Pressure Plate")
        builder.add(WitcheryBlocks.ROWAN_BUTTON.get(), "Rowan Button")
        builder.add(WitcheryBlocks.ROWAN_SAPLING.get(), "Rowan Sapling")
        builder.add(WitcheryBlocks.POTTED_ROWAN_SAPLING.get(), "Potted Rowan Sapling")
        builder.add(WitcheryBlocks.ROWAN_SIGN.get(), "Rowan Sign")
        builder.add(WitcheryBlocks.ROWAN_HANGING_SIGN.get(), "Rowan Hanging Sign")
        builder.add(WitcheryItems.ROWAN_BOAT.get(), "Rowan Boat")
        builder.add(WitcheryItems.ROWAN_CHEST_BOAT.get(), "Rowan Chest Boat")

        builder.add(WitcheryBlocks.ALDER_LOG.get(), "Alder Log")
        builder.add(WitcheryBlocks.ALDER_WOOD.get(), "Alder Wood")
        builder.add(WitcheryBlocks.STRIPPED_ALDER_LOG.get(), "Stripped Alder Log")
        builder.add(WitcheryBlocks.STRIPPED_ALDER_WOOD.get(), "Stripped Alder Wood")
        builder.add(WitcheryBlocks.ALDER_LEAVES.get(), "Alder Leaves")
        builder.add(WitcheryBlocks.ALDER_PLANKS.get(), "Alder Planks")
        builder.add(WitcheryBlocks.ALDER_STAIRS.get(), "Alder Stairs")
        builder.add(WitcheryBlocks.ALDER_SLAB.get(), "Alder Slab")
        builder.add(WitcheryBlocks.ALDER_FENCE.get(), "Alder Fence")
        builder.add(WitcheryBlocks.ALDER_FENCE_GATE.get(), "Alder Fence Gate")
        builder.add(WitcheryBlocks.ALDER_DOOR.get(), "Alder Door")
        builder.add(WitcheryBlocks.ALDER_TRAPDOOR.get(), "Alder Trapdoor")
        builder.add(WitcheryBlocks.ALDER_PRESSURE_PLATE.get(), "Alder Pressure Plate")
        builder.add(WitcheryBlocks.ALDER_BUTTON.get(), "Alder Button")
        builder.add(WitcheryBlocks.ALDER_SAPLING.get(), "Alder Sapling")
        builder.add(WitcheryBlocks.POTTED_ALDER_SAPLING.get(), "Potted Alder Sapling")
        builder.add(WitcheryBlocks.ALDER_SIGN.get(), "Alder Sign")
        builder.add(WitcheryBlocks.ALDER_HANGING_SIGN.get(), "Alder Hanging Sign")
        builder.add(WitcheryItems.ALDER_BOAT.get(), "Alder Boat")
        builder.add(WitcheryItems.ALDER_CHEST_BOAT.get(), "Alder Chest Boat")

        builder.add(WitcheryBlocks.HAWTHORN_LOG.get(), "Hawthorn Log")
        builder.add(WitcheryBlocks.HAWTHORN_WOOD.get(), "Hawthorn Wood")
        builder.add(WitcheryBlocks.STRIPPED_HAWTHORN_LOG.get(), "Stripped Hawthorn Log")
        builder.add(WitcheryBlocks.STRIPPED_HAWTHORN_WOOD.get(), "Stripped Hawthorn Wood")
        builder.add(WitcheryBlocks.HAWTHORN_LEAVES.get(), "Hawthorn Leaves")
        builder.add(WitcheryBlocks.HAWTHORN_PLANKS.get(), "Hawthorn Planks")
        builder.add(WitcheryBlocks.HAWTHORN_STAIRS.get(), "Hawthorn Stairs")
        builder.add(WitcheryBlocks.HAWTHORN_SLAB.get(), "Hawthorn Slab")
        builder.add(WitcheryBlocks.HAWTHORN_FENCE.get(), "Hawthorn Fence")
        builder.add(WitcheryBlocks.HAWTHORN_FENCE_GATE.get(), "Hawthorn Fence Gate")
        builder.add(WitcheryBlocks.HAWTHORN_DOOR.get(), "Hawthorn Door")
        builder.add(WitcheryBlocks.HAWTHORN_TRAPDOOR.get(), "Hawthorn Trapdoor")
        builder.add(WitcheryBlocks.HAWTHORN_PRESSURE_PLATE.get(), "Hawthorn Pressure Plate")
        builder.add(WitcheryBlocks.HAWTHORN_BUTTON.get(), "Hawthorn Button")
        builder.add(WitcheryBlocks.HAWTHORN_SAPLING.get(), "Hawthorn Sapling")
        builder.add(WitcheryBlocks.POTTED_HAWTHORN_SAPLING.get(), "Potted Hawthorn Sapling")
        builder.add(WitcheryBlocks.HAWTHORN_SIGN.get(), "Hawthorn Sign")
        builder.add(WitcheryBlocks.HAWTHORN_HANGING_SIGN.get(), "Hawthorn Hanging Sign")
        builder.add(WitcheryItems.HAWTHORN_BOAT.get(), "Hawthorn Boat")
        builder.add(WitcheryItems.HAWTHORN_CHEST_BOAT.get(), "Hawthorn Chest Boat")

        builder.add(WitcheryBlocks.BLOOD_POPPY.get(), "Blood Poppy")

        builder.add(WitcheryEntityTypes.MANDRAKE.get(), "Mandrake")

        builder.add(WitcheryTags.ROWAN_LOG_ITEMS, "Rowan Logs")
        builder.add(WitcheryTags.ALDER_LOG_ITEMS, "Alder Logs")
        builder.add(WitcheryTags.HAWTHORN_LOG_ITEMS, "Hawthorn Logs")
        builder.add(WitcheryTags.LEAF_ITEMS, "Witchery Leaves")
        builder.add(WitcheryTags.CANDELABRA_ITEMS, "Candelabras")

        builder.add("entity.witchery.rowan_boat", "Rowan Boat")
        builder.add("entity.witchery.rowan_chest_boat", "Rowan Chest Boat")
        builder.add("entity.witchery.alder_boat", "Alder Boat")
        builder.add("entity.witchery.alder_chest_boat", "Alder Chest Boat")
        builder.add("entity.witchery.hawthorn_boat", "Hawthorn Boat")
        builder.add("entity.witchery.hawthorn_chest_boat", "Hawthorn Chest Boat")



        builder.add("witchery:ritual/rite_of_charging_infusion", "Rite of Charging")
        builder.add("witchery:ritual/rite_of_charging_infusion.tooltip", "Charges the power of an Infused player")
        builder.add("witchery:ritual/infuse_light", "Infusion of Light")
        builder.add("witchery:ritual/infuse_light.tooltip", "Infuses the player with the Ghost of the Light")
        builder.add("witchery:ritual/infuse_otherwhere", "Infusion of Otherwhere")
        builder.add("witchery:ritual/infuse_otherwhere.tooltip", "Infuses the player with the Spirit of Otherwhere")

        builder.add("witchery:ritual/charge_attuned", "Rite of Charging")
        builder.add("witchery:ritual/charge_attuned.tooltip", "Charges an Attuned Stone with 2000 Altar Power")
        builder.add("witchery:ritual/summon_lightning_on_waystone", "Lightning Strike")
        builder.add("witchery:ritual/summon_lightning_on_waystone.tooltip", "Summons a Lightning Strike at bound Waystone location")
        builder.add("witchery:ritual/summon_lightning", "Lightning Strike")
        builder.add("witchery:ritual/summon_lightning.tooltip", "Summons a Lightning Strike at ritual center")
        builder.add("witchery:ritual/set_midnight", "Turn Night")
        builder.add("witchery:ritual/set_midnight.tooltip", "Sets the time to midnight")
        builder.add("witchery:ritual/push_mobs", "Rite of Sanctity")
        builder.add("witchery:ritual/push_mobs.tooltip", "Pushes hostile mobs away from ritual center")
        builder.add("witchery:ritual/teleport_owner_to_waystone", "Teleportation")
        builder.add("witchery:ritual/teleport_owner_to_waystone.tooltip", "Teleports the user to bound Waystone location")
        builder.add("witchery:ritual/teleport_taglock_to_waystone", "Teleportation")
        builder.add("witchery:ritual/teleport_taglock_to_waystone.tooltip", "Teleports the bound Taglock entity to bound Waystone location")
        builder.add("witchery:ritual/summon_imp", "Summon Imp")
        builder.add("witchery:ritual/summon_imp.tooltip", "Summon an Imp at ritual center")



        //GUIDEBOOK GENERAL
        builder.add("book.witchery.guidebook.general.name", "General")
        builder.add("book.witchery.guidebook.brewing.name", "Brewing")
        builder.add("book.witchery.guidebook.ritual.name", "Rituals")


        builder.add("book.witchery.guidebook.general.beginning.name", "Beginning")
        builder.add("book.witchery.guidebook.general.beginning.description", "Essential Witchery resources")
        builder.add("general.beginning.title", "Essential Witchery Resources")
        builder.add("general.beginning.page.1", "Nature and seeds good, break grass to get cool seeds")


        builder.add("book.witchery.guidebook.general.cauldron.name", "Cauldron")
        builder.add("book.witchery.guidebook.general.cauldron.description", "A watched pot never boils")
        builder.add("general.cauldron.title", "Witches Cauldron")
        builder.add("general.cauldron.page.1", "Lets cook")

        builder.add("book.witchery.guidebook.general.oven.name", "Oven")
        builder.add("book.witchery.guidebook.general.oven.description", "Smells like home")
        builder.add("general.oven.title", "Witches Oven")
        builder.add("general.oven.page.1", "Lets cook")

        builder.add("book.witchery.guidebook.general.distillery.name", "Distillery")
        builder.add("book.witchery.guidebook.general.distillery.description", "Smells like home")
        builder.add("general.distillery.title", "Distillery")
        builder.add("general.distillery.page.1", "Lets cook")

        builder.add("general.mutandis.mutandis", "Mutandis")
        builder.add("general.oven.breath_of_the_goddess", "Breath of the Goddess")
        builder.add("general.oven.hint_of_rebirth", "Hint of Rebirth")
        builder.add("general.oven.exhale_of_the_horned_one", "Exhale of the Horned One")
        builder.add("general.oven.foul_fume_logs", "Foul Fume")
        builder.add("general.oven.whiff_of_magic", "Whiff of Magic")
        builder.add("general.oven.odor_of_purity", "Odor of Purity")
        builder.add("general.oven.reek_of_misfortune", "Reek of Misfortune")

        builder.add("general.distillery.oil_of_vitriol_gypsum", "Oil of Vitriol")
        builder.add("general.distillery.demons_blood", "Demons Blood")
        builder.add("general.distillery.ender_dew", "Ender Dew")
        builder.add("general.distillery.phantom_vapor", "Phantom Vapor")
        builder.add("general.distillery.reek_of_misfortune", "Reek of Misfortune")
        builder.add("general.distillery.refined_evil", "Refined Evil")
        builder.add("general.distillery.tear_and_whiff", "Tear of the Goddess")

        builder.add("book.witchery.guidebook.general.mutandis.name", "Mutandis")
        builder.add("book.witchery.guidebook.general.mutandis.description", "CRISPR that plant")
        builder.add("general.mutandis.title", "Mutandis")
        builder.add("general.mutandis.page.1", "Evil Scrambled Eggs")

        builder.add("book.witchery.guidebook.general.whiff_of_magic.name", "Whiff of Magic")
        builder.add("book.witchery.guidebook.general.whiff_of_magic.description", "Smells like potpourri")
        builder.add("general.whiff_of_magic.title", "Whiff of Magic")
        builder.add("general.whiff_of_magic.page.1", "Smells like potpourri")

        builder.add("book.witchery.guidebook.general.exhale_of_the_horned_one.name", "Exhale of the Horned One")
        builder.add("book.witchery.guidebook.general.exhale_of_the_horned_one.description", "Smells like mold")
        builder.add("general.exhale_of_the_horned_one.title", "Exhale of the Horned One")
        builder.add("general.exhale_of_the_horned_one.page.1", "Everything reminds me of him")

        builder.add("book.witchery.guidebook.general.hint_of_rebirth.name", "Hint of Rebirth")
        builder.add("book.witchery.guidebook.general.hint_of_rebirth.description", "Smells like lime")
        builder.add("general.hint_of_rebirth.title", "Hint of Rebirth")
        builder.add("general.hint_of_rebirth.page.1", "Wise words")

        builder.add("book.witchery.guidebook.general.breath_of_the_goddess.name", "Breath of the Goddess")
        builder.add("book.witchery.guidebook.general.breath_of_the_goddess.description", "Smells nice")
        builder.add("general.breath_of_the_goddess.title", "Breath of the Goddess")
        builder.add("general.breath_of_the_goddess.page.1", "Wise words")

        builder.add("book.witchery.guidebook.general.tear_of_the_goddess.name", "Tear of the Goddess")
        builder.add("book.witchery.guidebook.general.tear_of_the_goddess.description", "Better than gamer girl bathwater")
        builder.add("general.tear_of_the_goddess.title", "Tear of the Goddess")
        builder.add("general.tear_of_the_goddess.page.1", "Wise words")

        //GUIDEBOOK BREWING
        builder.add("book.witchery.guidebook.brewing.cauldron.name", "Cauldron")
        builder.add("book.witchery.guidebook.brewing.cauldron.description", "Swarley")
        builder.add("brewing.cauldron.title", "Cauldron")
        builder.add("brewing.cauldron.page.1", "Its not supposed to be brown, most of the time")

        builder.add("book.witchery.guidebook.brewing.ritual_chalk.name", "Ritual Chalk")
        builder.add("book.witchery.guidebook.brewing.ritual_chalk.description", "Better than crayons")
        builder.add("brewing.ritual_chalk.title", "Ritual Chalk")
        builder.add("brewing.ritual_chalk.page.1", "B")

        builder.add("book.witchery.guidebook.brewing.redstone_soup.name", "Redstone Soup")
        builder.add("book.witchery.guidebook.brewing.redstone_soup.description", "Got Soup?")
        builder.add("brewing.redstone_soup.title", "Redstone Soup")
        builder.add("brewing.redstone_soup.page.1", "Soup")

        builder.add("brewing.redstone_soup.redstone_soup", "Redstone Soup")
        builder.add("brewing.ritual_chalk.golden_chalk", "Golden Chalk")
        builder.add("brewing.ritual_chalk.infernal_chalk", "Infernal Chalk")
        builder.add("brewing.ritual_chalk.otherwhere_chalk", "Otherwhere Chalk")

        //GUIDEBOOK RITUALS
        builder.add("book.witchery.guidebook.ritual.ritual_chalk.name", "Ritual Chalk")
        builder.add("book.witchery.guidebook.ritual.ritual_chalk.description", "Better than crayons")
        builder.add("ritual.ritual_chalk.title", "Ritual Chalk")
        builder.add("ritual.ritual_chalk.page.1", "B")

        builder.add("book.witchery.guidebook.ritual.golden_chalk.name", "Golden Chalk")
        builder.add("book.witchery.guidebook.ritual.golden_chalk.description", "Better yellow than crayons")
        builder.add("ritual.golden_chalk.title", "Golden Chalk")
        builder.add("ritual.golden_chalk.page.1", "G")

        builder.add("book.witchery.guidebook.ritual.infernal_chalk.name", "Infernal Chalk")
        builder.add("book.witchery.guidebook.ritual.infernal_chalk.description", "Better red than crayons")
        builder.add("ritual.infernal_chalk.title", "Infernal Chalk")
        builder.add("ritual.infernal_chalk.page.1", "I")

        builder.add("book.witchery.guidebook.ritual.otherwhere_chalk.name", "Otherwhere Chalk")
        builder.add("book.witchery.guidebook.ritual.otherwhere_chalk.description", "Better purple than crayons")
        builder.add("ritual.otherwhere_chalk.title", "Otherwhere Chalk")
        builder.add("ritual.otherwhere_chalk.page.1", "I")


        builder.add("ritual.ritual_chalk.otherwhere_chalk", "Otherwhere Chalk")
        builder.add("ritual.ritual_chalk.infernal_chalk", "Infernal Chalk")
        builder.add("ritual.ritual_chalk.golden_chalk", "Golden Chalk")
    }
}